/**
 * useResultCards — result-card (Ed-Fi ReportCard) hooks.
 *
 * Result cards are generated by the backend when an exam closes. This slice
 * lists them per exam and supports conduct/remark edits + the terminal publish.
 * Single-card mutations always pass enrollmentId (Invariant 3).
 */

import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { toast } from 'sonner'
import type { ResultCardListResponseDto, ResultCardResponseDto } from '@aibrains/shared-types'
import {
  getResultCards,
  updateResultCardConduct,
  updateResultCardRemark,
  publishResultCard,
  parseApiError,
  type ResultCardListParams,
} from '../services/academics.service'

export const resultCardKeys = {
  all: ['result-cards'] as const,
  lists: () => [...resultCardKeys.all, 'list'] as const,
  list: (params: ResultCardListParams) => [...resultCardKeys.lists(), params] as const,
}

/**
 * List result cards for an exam (or other scope).
 */
export function useResultCards(params: ResultCardListParams, enabled = true) {
  return useQuery<ResultCardListResponseDto, Error>({
    queryKey: resultCardKeys.list(params),
    queryFn: () => getResultCards(params),
    enabled: enabled && (!!params.examId || !!params.enrollmentId || !!params.studentId || !!params.schoolId),
    staleTime: 30 * 1000,
  })
}

interface ConductVars {
  cardId: string
  enrollmentId: string
  conduct: string
}

export function useUpdateResultCardConduct() {
  const queryClient = useQueryClient()
  return useMutation<ResultCardResponseDto, Error, ConductVars>({
    mutationFn: ({ cardId, enrollmentId, conduct }) => updateResultCardConduct(cardId, enrollmentId, conduct),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: resultCardKeys.lists() })
      toast.success('Conduct updated')
    },
    onError: (error) => toast.error(parseApiError(error).message),
  })
}

interface RemarkVars {
  cardId: string
  enrollmentId: string
  classTeacherRemark: string
}

export function useUpdateResultCardRemark() {
  const queryClient = useQueryClient()
  return useMutation<ResultCardResponseDto, Error, RemarkVars>({
    mutationFn: ({ cardId, enrollmentId, classTeacherRemark }) =>
      updateResultCardRemark(cardId, enrollmentId, classTeacherRemark),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: resultCardKeys.lists() })
      toast.success('Remark updated')
    },
    onError: (error) => toast.error(parseApiError(error).message),
  })
}

interface PublishVars {
  cardId: string
  enrollmentId: string
  notes?: string
}

export function usePublishResultCard() {
  const queryClient = useQueryClient()
  return useMutation<ResultCardResponseDto, Error, PublishVars>({
    mutationFn: ({ cardId, enrollmentId, notes }) => publishResultCard(cardId, enrollmentId, notes),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: resultCardKeys.lists() })
      toast.success('Result card published')
    },
    onError: (error) => toast.error(parseApiError(error).message),
  })
}
