/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      colors: {
        // EdForge Brand Colors - Coolors Palette
        ink: {
          50: '#9ee4ff',
          100: '#3dc8ff',
          200: '#009ddb',
          300: '#00587a',
          400: '#002a3d',
          500: '#001219',
          600: '#000f14',
          700: '#000b0f',
          800: '#00070a',
          900: '#000405',
        },
        teal: {
          50: '#b0f2ff',
          100: '#62e5ff',
          200: '#13d8ff',
          300: '#00a3c4',
          400: '#007a93',
          500: '#005f73',
          600: '#004e5e',
          700: '#003b46',
          800: '#00272f',
          900: '#001417',
        },
        cyan: {
          50: '#bdfafb',
          100: '#7bf4f7',
          200: '#39eff2',
          300: '#0ed3d7',
          400: '#0ab3b6',
          500: '#0a9396',
          600: '#087577',
          700: '#065859',
          800: '#043b3b',
          900: '#021d1e',
        },
        aqua: {
          50: '#e9f6f2',
          100: '#d4ede5',
          200: '#bee4d7',
          300: '#a9dbca',
          400: '#94d2bd',
          500: '#7ac4ab',
          600: '#61bd9e',
          700: '#3f977a',
          800: '#2a6551',
          900: '#153229',
        },
        vanilla: {
          50: '#fbf7ed',
          100: '#f6efdb',
          200: '#f2e7c9',
          300: '#ede0b7',
          400: '#e9d8a6',
          500: '#d9bc66',
          600: '#bf9b30',
          700: '#7f6720',
          800: '#403410',
          900: '#201a08',
        },
        golden: {
          50: '#ffecc9',
          100: '#ffd993',
          200: '#ffc65d',
          300: '#ffb327',
          400: '#ee9b00',
          500: '#c07d00',
          600: '#905d00',
          700: '#603e00',
          800: '#301f00',
          900: '#180f00',
        },
        caramel: {
          50: '#fee0c2',
          100: '#fec286',
          200: '#fda349',
          300: '#fd850d',
          400: '#ca6702',
          500: '#a25202',
          600: '#793d01',
          700: '#512901',
          800: '#281400',
          900: '#140a00',
        },
        rust: {
          50: '#f9cac6',
          100: '#f3958d',
          200: '#ed6053',
          300: '#e72b1a',
          400: '#ae2012',
          500: '#8c190f',
          600: '#69130b',
          700: '#460d07',
          800: '#230604',
          900: '#110302',
        },
        // Semantic colors using CSS vars
        surface: {
          primary: 'rgb(var(--background-primary) / <alpha-value>)',
          secondary: 'rgb(var(--background-secondary) / <alpha-value>)',
          tertiary: 'rgb(var(--background-tertiary) / <alpha-value>)',
          elevated: 'rgb(var(--background-elevated) / <alpha-value>)',
        },
        background: {
          primary: 'rgb(var(--background-primary) / <alpha-value>)',
          secondary: 'rgb(var(--background-secondary) / <alpha-value>)',
          tertiary: 'rgb(var(--background-tertiary) / <alpha-value>)',
          elevated: 'rgb(var(--background-elevated) / <alpha-value>)',
          overlay: 'rgb(var(--background-overlay) / <alpha-value>)',
          inverse: 'rgb(var(--background-inverse) / <alpha-value>)',
        },
        text: {
          primary: 'rgb(var(--text-primary) / <alpha-value>)',
          secondary: 'rgb(var(--text-secondary) / <alpha-value>)',
          tertiary: 'rgb(var(--text-tertiary) / <alpha-value>)',
          inverted: 'rgb(var(--text-inverted) / <alpha-value>)',
          muted: 'rgb(var(--text-muted) / <alpha-value>)',
          disabled: 'rgb(var(--text-disabled) / <alpha-value>)',
          onAccent: 'rgb(var(--text-on-accent) / <alpha-value>)',
        },
        border: {
          primary: 'rgb(var(--border-primary) / <alpha-value>)',
          secondary: 'rgb(var(--border-secondary) / <alpha-value>)',
          tertiary: 'rgb(var(--border-tertiary) / <alpha-value>)',
          subtle: 'rgb(var(--border-subtle) / <alpha-value>)',
          DEFAULT: 'rgb(var(--border-default) / <alpha-value>)',
          strong: 'rgb(var(--border-strong) / <alpha-value>)',
          focus: 'rgb(var(--border-focus) / <alpha-value>)',
        },
        brand: {
          primary: 'rgb(var(--action-primary-bg) / <alpha-value>)',
          secondary: 'rgb(var(--state-info-fg) / <alpha-value>)',
          accent: 'rgb(var(--state-warning-fg) / <alpha-value>)',
        },
        action: {
          primary: {
            DEFAULT: 'rgb(var(--action-primary-bg) / <alpha-value>)',
            hover: 'rgb(var(--action-primary-bg-hover) / <alpha-value>)',
            active: 'rgb(var(--action-primary-bg-active) / <alpha-value>)',
            fg: 'rgb(var(--action-primary-fg) / <alpha-value>)',
          },
          secondary: {
            DEFAULT: 'rgb(var(--action-secondary-bg) / <alpha-value>)',
            fg: 'rgb(var(--action-secondary-fg) / <alpha-value>)',
          },
          danger: {
            DEFAULT: 'rgb(var(--action-danger-bg) / <alpha-value>)',
            fg: 'rgb(var(--action-danger-fg) / <alpha-value>)',
          },
        },
        state: {
          success: {
            bg: 'rgb(var(--state-success-bg) / <alpha-value>)',
            fg: 'rgb(var(--state-success-fg) / <alpha-value>)',
            border: 'rgb(var(--state-success-border) / <alpha-value>)',
          },
          warning: {
            bg: 'rgb(var(--state-warning-bg) / <alpha-value>)',
            fg: 'rgb(var(--state-warning-fg) / <alpha-value>)',
            border: 'rgb(var(--state-warning-border) / <alpha-value>)',
          },
          danger: {
            bg: 'rgb(var(--state-danger-bg) / <alpha-value>)',
            fg: 'rgb(var(--state-danger-fg) / <alpha-value>)',
            border: 'rgb(var(--state-danger-border) / <alpha-value>)',
          },
          info: {
            bg: 'rgb(var(--state-info-bg) / <alpha-value>)',
            fg: 'rgb(var(--state-info-fg) / <alpha-value>)',
            border: 'rgb(var(--state-info-border) / <alpha-value>)',
          },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.2s ease-out',
        'slide-up': 'slide-up 0.3s ease-out',
        'slide-in-right': 'slide-in-right 0.3s ease-out',
      },
      boxShadow: {
        flat: 'var(--elevation-flat)',
        raised: 'var(--elevation-raised)',
        overlay: 'var(--elevation-overlay)',
        modal: 'var(--elevation-modal)',
        popover: 'var(--elevation-popover)',
      },
      transitionDuration: {
        instant: 'var(--motion-duration-instant)',
        fast: 'var(--motion-duration-fast)',
        base: 'var(--motion-duration-base)',
        slow: 'var(--motion-duration-slow)',
      },
      transitionTimingFunction: {
        standard: 'var(--motion-easing-standard)',
        enter: 'var(--motion-easing-enter)',
        exit: 'var(--motion-easing-exit)',
      },
      keyframes: {
        'fade-in': {
          from: { opacity: '0', transform: 'translateY(-8px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-up': {
          from: { opacity: '0', transform: 'translateY(16px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-in-right': {
          from: { opacity: '0', transform: 'translateX(16px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
      },
    },
  },
  plugins: [],
}

