/**
 * CourseForm Component
 *
 * Form for creating and editing courses, organized by section.
 * Uses @edforge/forms fields with react-hook-form context.
 * Must be wrapped in a FormProvider.
 */

import { useEffect, useMemo } from 'react'
import { useFieldArray, useFormContext } from '@edforge/forms'
import {
  TextField,
  SelectField,
  TextareaField,
  FormSection,
} from '@edforge/forms'
import { Input, Tooltip, InlineAlert } from '@edforge/ui'
import {
  Hash,
  BookOpen,
  GraduationCap,
  Clock,
  Award,
  Plus,
  X,
  RotateCw,
  AlertTriangle,
} from 'lucide-react'
import type { AcademicSubjectDescriptor } from '@aibrains/shared-types'
import {
  ACADEMIC_SUBJECT_OPTIONS,
  COURSE_TYPE_OPTIONS,
  CREDIT_TYPE_OPTIONS,
  DURATION_OPTIONS,
  GRADE_LEVEL_OPTIONS,
  MATERIAL_TYPE_OPTIONS,
  generateCourseCode,
  dedupeCourseCode,
  type CourseFormData,
} from '../../schemas/course.form'
import { useAcademicsI18n } from '../../lib/i18n'
import { useSchoolEnabledGradeOptions } from '../../hooks/useGradeOptions'

// ============================================================================
// TYPES
// ============================================================================

interface CourseFormProps {
  /** Whether course code field is locked (edit mode) */
  isEdit?: boolean
  /**
   * School ID. The grade-level multi-select reads
   * `school.enabledGradeLevels` (with `gradeRange` fallback) to scope the
   * pickable codes. Pass null when no school is active.
   */
  schoolId: string | null
  /**
   * Course codes already in the catalog (loaded pages). Used to de-duplicate
   * the auto-generated course code (best-effort; the backend 409 is the
   * authoritative uniqueness guard).
   */
  existingCourseCodes?: string[]
}

// ============================================================================
// COURSE CODE AUTO-FILL (create mode)
// ============================================================================

/**
 * Suggests a compliant course code from the chosen Academic Subject + Grade
 * Levels and keeps it in sync — until the operator edits the code manually, at
 * which point it becomes a custom value and stops auto-updating. "Regenerate"
 * re-derives and re-enables auto-fill. Only rendered in create mode.
 */
function CourseCodeAutoFill({
  existingCourseCodes = [],
}: {
  existingCourseCodes?: string[]
}) {
  const { t } = useAcademicsI18n()
  const { watch, setValue, getValues, resetField, formState } =
    useFormContext<CourseFormData>()
  const academicSubject = watch('academicSubject') as
    | AcademicSubjectDescriptor
    | undefined
  const gradeLevels = (watch('gradeLevels') ?? []) as string[]
  // Reading dirtyFields here subscribes the component to its changes (RHF proxy).
  const isCustom = Boolean(formState.dirtyFields.courseCode)
  const gradeKey = gradeLevels.join(',')
  const canGenerate = Boolean(academicSubject) && gradeLevels.length > 0

  useEffect(() => {
    if (isCustom || !canGenerate) return
    const next = dedupeCourseCode(
      generateCourseCode(academicSubject, gradeLevels),
      existingCourseCodes
    )
    if (next && next !== getValues('courseCode')) {
      setValue('courseCode', next, { shouldDirty: false, shouldValidate: true })
    }
    // existingCourseCodes is a fresh array each render; gradeKey + subject +
    // isCustom are the inputs that should re-derive the suggestion.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [academicSubject, gradeKey, isCustom])

  const handleRegenerate = () => {
    if (!canGenerate) return
    const next = dedupeCourseCode(
      generateCourseCode(academicSubject, gradeLevels),
      existingCourseCodes
    )
    // resetField makes `next` the new pristine default, clearing the manual-edit
    // flag so the field resumes auto-updating with subject/grade changes.
    resetField('courseCode', { defaultValue: next })
  }

  return (
    <div className="mt-1.5 flex items-center justify-between gap-2">
      <p className="text-xs text-text-tertiary">
        {isCustom
          ? t('curriculumModule.form.courseCodeCustom')
          : t('curriculumModule.form.courseCodeAutoGenerated')}
      </p>
      <button
        type="button"
        onClick={handleRegenerate}
        disabled={!canGenerate}
        className="inline-flex items-center gap-1 text-xs font-medium text-[rgb(var(--action-secondary-fg))] hover:text-[rgb(var(--text-primary))] disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
      >
        <RotateCw className="w-3 h-3" />
        {t('curriculumModule.form.regenerate')}
      </button>
    </div>
  )
}

// ============================================================================
// GRADE LEVEL MULTI-SELECT
// ============================================================================

function GradeLevelSelector({
  schoolId,
}: {
  schoolId: string | null
}) {
  const { t } = useAcademicsI18n()
  const { watch, setValue, formState: { errors } } = useFormContext()
  const selected: string[] = watch('gradeLevels') ?? []
  const { options: baseOptions } = useSchoolEnabledGradeOptions(schoolId)

  // Include any already-selected grades that fall outside the school range
  // (edge case: school range narrowed after course creation)
  const options = useMemo(() => {
    const baseValues = new Set<string>(baseOptions.map((o) => o.value))
    const outOfRange = selected
      .filter((v) => !baseValues.has(v))
      .map((v) => GRADE_LEVEL_OPTIONS.find((o) => o.value === v))
      .filter(Boolean) as (typeof GRADE_LEVEL_OPTIONS)[number][]
    return outOfRange.length > 0 ? [...baseOptions, ...outOfRange] : baseOptions
  }, [baseOptions, selected])

  const toggle = (value: string) => {
    const next = selected.includes(value)
      ? selected.filter((v) => v !== value)
      : [...selected, value]
    setValue('gradeLevels', next, { shouldValidate: true })
  }

  const error = errors?.gradeLevels?.message as string | undefined
  const baseValues = new Set<string>(baseOptions.map((o) => o.value))

  return (
    <div>
      <label className="block text-sm font-medium text-text-primary mb-2">
        {t('tables.courses.columns.grades')} <span className="text-[rgb(var(--state-danger-fg))]">*</span>
      </label>
      <div className="flex flex-wrap gap-2">
        {options.map((opt) => {
          const isSelected = selected.includes(opt.value)
          const isOutOfRange = !baseValues.has(opt.value)
          return (
            <button
              key={opt.value}
              type="button"
              onClick={() => toggle(opt.value)}
              className={`px-3 py-1.5 rounded-lg text-sm font-medium border transition-all ${
                isSelected
                  ? isOutOfRange
                    ? 'bg-[rgb(var(--state-warning-fg))] text-[rgb(var(--action-primary-fg))] border-amber-500 shadow-sm'
                    : 'bg-[rgb(var(--action-primary-bg))] text-[rgb(var(--action-primary-fg))] border-[rgb(var(--border-focus))] shadow-sm'
                  : isOutOfRange
                    ? 'bg-surface-primary text-amber-500 border-amber-300 border-dashed hover:border-amber-400'
                    : 'bg-surface-primary text-text-secondary border-border-primary hover:border-[rgb(var(--border-focus))] hover:text-text-primary'
              }`}
              title={isOutOfRange ? t('curriculumModule.form.outsideSchoolGradeRange') : undefined}
            >
              {opt.label}
            </button>
          )
        })}
      </div>
      {error && (
        <p className="mt-1.5 text-sm text-[rgb(var(--state-danger-fg))]">{error}</p>
      )}
    </div>
  )
}

// ============================================================================
// OBJECTIVES TAG INPUT
// ============================================================================

function ObjectivesInput() {
  const { t, formatNumber } = useAcademicsI18n()
  const { watch, setValue } = useFormContext()
  const objectives: string[] = watch('objectives') ?? []

  const addObjective = (value: string) => {
    if (value.trim() && objectives.length < 20) {
      setValue('objectives', [...objectives, value.trim()], { shouldValidate: true })
    }
  }

  const removeObjective = (index: number) => {
    setValue('objectives', objectives.filter((_, i) => i !== index), { shouldValidate: true })
  }

  return (
    <div>
      <label className="block text-sm font-medium text-text-primary mb-2">
        {t('curriculumModule.form.learningObjectives')}
      </label>
      <div className="space-y-2">
        {objectives.map((obj, i) => (
          <div
            key={i}
            className="flex items-center gap-2 px-3 py-2 bg-surface-secondary rounded-lg border border-border-secondary"
          >
            <span className="flex-1 text-sm text-text-primary">{obj}</span>
            <button
              type="button"
              onClick={() => removeObjective(i)}
              className="p-0.5 rounded text-text-tertiary hover:text-[rgb(var(--state-danger-fg))] transition-colors"
            >
              <X className="w-3.5 h-3.5" />
            </button>
          </div>
        ))}
        {objectives.length < 20 && (
          <Input
            placeholder={t('curriculumModule.form.objectivePlaceholder')}
            onKeyDown={(e) => {
              if (e.key === 'Enter') {
                e.preventDefault()
                addObjective(e.currentTarget.value)
                e.currentTarget.value = ''
              }
            }}
          />
        )}
      </div>
      <p className="mt-1 text-xs text-text-tertiary">
        {t('curriculumModule.form.objectiveCount', {
          count: formatNumber(objectives.length),
          max: formatNumber(20),
        })}
      </p>
    </div>
  )
}

// ============================================================================
// MATERIALS LIST
// ============================================================================

function MaterialsList() {
  const { t } = useAcademicsI18n()
  const { control } = useFormContext()
  const { fields, append, remove } = useFieldArray({
    control,
    name: 'textbooks',
  })

  return (
    <div>
      <div className="flex items-center justify-between mb-3">
        <label className="text-sm font-medium text-text-primary">
          {t('curriculumModule.form.materialsTitle')}
        </label>
        <button
          type="button"
          onClick={() =>
            append({
              type: 'textbook',
              title: '',
              author: '',
              isbn: '',
              isRequired: true,
            })
          }
          className="flex items-center gap-1 px-2 py-1 text-xs font-medium text-[rgb(var(--action-secondary-fg))] hover:text-[rgb(var(--text-primary))] hover:bg-[rgb(var(--state-info-bg)/0.18)] rounded-md transition-colors"
        >
          <Plus className="w-3.5 h-3.5" />
          {t('curriculumModule.form.addMaterial')}
        </button>
      </div>

      {fields.length === 0 ? (
        <p className="text-sm text-text-tertiary py-2">
          {t('curriculumModule.form.noMaterials')}
        </p>
      ) : (
        <div className="space-y-3">
          {fields.map((field, index) => (
            <div
              key={field.id}
              className="p-4 bg-surface-secondary rounded-lg border border-border-secondary space-y-3"
            >
              <div className="flex items-center justify-between">
                <span className="text-xs font-medium text-text-secondary uppercase tracking-wide">
                  {t('curriculumModule.form.materialNumber', { number: index + 1 })}
                </span>
                <button
                  type="button"
                  onClick={() => remove(index)}
                  className="p-1 rounded text-text-tertiary hover:text-[rgb(var(--state-danger-fg))] transition-colors"
                >
                  <X className="w-4 h-4" />
                </button>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div className="col-span-2 sm:col-span-1">
                  <SelectField
                    name={`textbooks.${index}.type`}
                    label={t('curriculumModule.form.materialType')}
                    options={MATERIAL_TYPE_OPTIONS.map((o) => ({
                      value: o.value,
                      label: t(`curriculumModule.form.materialTypes.${o.value}`),
                    }))}
                  />
                </div>

                <div className="col-span-2 sm:col-span-1">
                  <TextField
                    name={`textbooks.${index}.title`}
                    label={t('curriculumModule.form.materialTitle')}
                    placeholder={t('curriculumModule.form.materialTitlePlaceholder')}
                  />
                </div>

                <TextField
                  name={`textbooks.${index}.author`}
                  label={t('curriculumModule.form.materialAuthor')}
                  placeholder={t('curriculumModule.form.materialAuthorPlaceholder')}
                />

                <TextField
                  name={`textbooks.${index}.isbn`}
                  label={t('curriculumModule.form.materialIsbn')}
                  placeholder={t('curriculumModule.form.materialIsbnPlaceholder')}
                />
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}

// ============================================================================
// COURSE FORM
// ============================================================================

export function CourseForm({ isEdit = false, schoolId, existingCourseCodes }: CourseFormProps) {
  const { t } = useAcademicsI18n()
  const { watch } = useFormContext<CourseFormData>()
  const academicSubject = watch('academicSubject')
  // Legacy courses created before academicSubject became required can load without
  // it; surface the gap in edit mode so the operator can complete the record.
  const subjectMissing = isEdit && !academicSubject

  return (
    <div className="space-y-8">
      {subjectMissing && (
        <InlineAlert variant="warning" title={t('curriculumModule.form.incompleteTitle')}>
          {t('curriculumModule.form.incompleteDescription')}
        </InlineAlert>
      )}

      {/* Section 1: Identity */}
      <FormSection
        title={t('curriculumModule.form.identityTitle')}
        description={t('curriculumModule.form.identityDescription')}
      >
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div>
            <TextField
              name="courseCode"
              label={t('curriculumModule.form.courseCode')}
              placeholder={t('curriculumModule.form.courseCodePlaceholder')}
              icon={Hash}
              disabled={isEdit}
            />
            {!isEdit && <CourseCodeAutoFill existingCourseCodes={existingCourseCodes} />}
          </div>
          <TextField
            name="courseName"
            label={t('tables.courses.columns.courseName')}
            placeholder={t('curriculumModule.form.courseNamePlaceholder')}
            icon={BookOpen}
          />
        </div>
      </FormSection>

      {/* Section 2: Classification */}
      <FormSection
        title={t('curriculumModule.form.classificationTitle')}
        description={t('curriculumModule.form.classificationDescription')}
      >
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <SelectField
            name="academicSubject"
            label={
              subjectMissing ? (
                <span className="inline-flex items-center gap-1">
                  {t('curriculumModule.form.academicSubject')}
                  <Tooltip content={t('curriculumModule.form.academicSubjectMissingTooltip')}>
                    <AlertTriangle className="w-3.5 h-3.5 text-[rgb(var(--state-warning-fg))]" />
                  </Tooltip>
                </span>
              ) : (
                t('curriculumModule.form.academicSubject')
              )
            }
            placeholder={t('curriculumModule.form.selectAcademicSubject')}
            options={ACADEMIC_SUBJECT_OPTIONS.map((o) => ({ value: o.value, label: o.label }))}
            icon={GraduationCap}
          />
          <SelectField
            name="courseType"
            label={t('tables.courses.columns.type')}
            placeholder={t('curriculumModule.form.selectCourseType')}
            options={COURSE_TYPE_OPTIONS.map((o) => ({ value: o.value, label: o.label }))}
          />
          <SelectField
            name="creditType"
            label={t('curriculumModule.form.creditType')}
            placeholder={t('curriculumModule.form.selectCreditType')}
            options={CREDIT_TYPE_OPTIONS.map((o) => ({ value: o.value, label: o.label }))}
            icon={Award}
          />
          <TextField
            name="credits"
            label={t('tables.courses.columns.credits')}
            type="number"
            placeholder={t('curriculumModule.form.creditsPlaceholder')}
          />
          <SelectField
            name="typicalDuration"
            label={t('tables.courses.columns.duration')}
            placeholder={t('curriculumModule.form.selectDuration')}
            options={DURATION_OPTIONS.map((o) => ({ value: o.value, label: o.label }))}
            icon={Clock}
          />
          <TextField
            name="periodsPerWeek"
            label={t('curriculumModule.form.periodsPerWeek')}
            type="number"
            placeholder={t('curriculumModule.form.periodsPerWeekPlaceholder')}
          />
        </div>
      </FormSection>

      {/* Section 3: Grade Levels */}
      <FormSection
        title={t('tables.courses.columns.grades')}
        description={t('curriculumModule.form.gradeLevelsDescription')}
      >
        <GradeLevelSelector schoolId={schoolId} />
      </FormSection>

      {/* Section 4: Description & Objectives */}
      <FormSection
        title={t('curriculumModule.form.descriptionObjectivesTitle')}
        description={t('curriculumModule.form.descriptionObjectivesDescription')}
      >
        <TextareaField
          name="description"
          label={t('curriculumModule.form.courseDescription')}
          placeholder={t('curriculumModule.form.courseDescriptionPlaceholder')}
        />
        <div className="mt-4">
          <ObjectivesInput />
        </div>
      </FormSection>

      {/* Section 5: Materials (optional) */}
      <FormSection
        title={t('curriculumModule.form.materialsTitle')}
        description={t('curriculumModule.form.materialsDescription')}
      >
        <MaterialsList />
      </FormSection>
    </div>
  )
}
