/**
 * Personal Information Step
 *
 * Step 1: Name, Staff ID, demographics.
 * Auto-generates staffUniqueId from firstName + lastSurname.
 */

import React, { useState, useEffect } from 'react'
import { motion } from 'framer-motion'
import type { WizardStepProps } from '@edforge/wizard'
import { useTranslation } from '@edforge/i18n'
import {
  GENDER_OPTIONS,
  SUFFIX_OPTIONS,
  generateStaffUniqueId,
  optionValueToI18nKey,
} from '../staff-wizard.utils'
import { AnimatedInput, AnimatedSelect, AnimatedCheckbox } from './shared'

export function PersonalInfoStep({ data, updateData, errors, clearError }: WizardStepProps) {
  const { t } = useTranslation('people')
  const [idWasAutoGenerated, setIdWasAutoGenerated] = useState(true)
  const genderOptions = GENDER_OPTIONS.map((option) => ({
    ...option,
    label: option.value
      ? t(`choices.gender.${optionValueToI18nKey(option.value)}`, { defaultValue: option.label })
      : t('common.select'),
  }))
  const suffixOptions = SUFFIX_OPTIONS.map((option) => ({
    ...option,
    label: option.value ? option.label : t('common.none'),
  }))

  const handleChange = (field: string) => (
    e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>,
  ) => {
    updateData({ [field]: e.target.value })
    clearError(field)
  }

  // Auto-generate staffUniqueId from name
  useEffect(() => {
    const firstName = data.firstName as string
    const lastName = data.lastSurname as string
    if (firstName && lastName && idWasAutoGenerated) {
      updateData({ staffUniqueId: generateStaffUniqueId(firstName, lastName) })
    }
  }, [data.firstName, data.lastSurname]) // eslint-disable-line react-hooks/exhaustive-deps

  return (
    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-5">
      {/* Name Fields */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <AnimatedInput
          label={t('fields.firstName')}
          required
          placeholder={t('wizard.placeholders.firstName')}
          autoComplete="given-name"
          value={(data.firstName as string) || ''}
          onChange={handleChange('firstName')}
          error={errors.firstName}
        />
        <AnimatedInput
          label={t('fields.lastName')}
          required
          placeholder={t('wizard.placeholders.lastName')}
          autoComplete="family-name"
          value={(data.lastSurname as string) || ''}
          onChange={handleChange('lastSurname')}
          error={errors.lastSurname}
        />
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <AnimatedInput
          label={t('fields.middleName')}
          placeholder={t('wizard.placeholders.middleName')}
          autoComplete="additional-name"
          value={(data.middleName as string) || ''}
          onChange={handleChange('middleName')}
        />
        <AnimatedInput
          label={t('fields.maidenName')}
          placeholder={t('wizard.placeholders.maidenName')}
          value={(data.maidenName as string) || ''}
          onChange={handleChange('maidenName')}
        />
        <AnimatedSelect
          label={t('fields.suffix')}
          value={(data.generationCodeSuffix as string) || ''}
          onChange={handleChange('generationCodeSuffix')}
          options={suffixOptions}
        />
      </div>

      {/* Staff ID */}
      <AnimatedInput
        label={t('fields.staffId')}
        required
        placeholder={t('wizard.placeholders.staffUniqueId')}
        value={(data.staffUniqueId as string) || ''}
        onChange={(e) => {
          setIdWasAutoGenerated(false)
          updateData({ staffUniqueId: e.target.value.toUpperCase() })
          clearError('staffUniqueId')
        }}
        error={errors.staffUniqueId}
        helpText={t('wizard.help.staffUniqueId')}
        className="font-mono uppercase"
      />

      {/* Demographics */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <AnimatedInput
          label={t('fields.dateOfBirth')}
          type="date"
          value={(data.birthDate as string) || ''}
          onChange={handleChange('birthDate')}
          error={errors.birthDate}
        />
        <AnimatedSelect
          label={t('fields.gender')}
          value={(data.gender as string) || ''}
          onChange={handleChange('gender')}
          options={genderOptions}
        />
      </div>

      <AnimatedCheckbox
        label={t('fields.hispanicLatinoEthnicity')}
        checked={data.hispanicLatinoEthnicity === true}
        onChange={(checked) => updateData({ hispanicLatinoEthnicity: checked })}
        helpText={t('wizard.help.edfiComplianceField')}
      />
    </motion.div>
  )
}
