/**
 * Personal Information Step
 *
 * Step 1: Name, Staff ID, demographics.
 * Auto-generates staffUniqueId from firstName + lastSurname.
 */

import React, { useState, useEffect } from 'react'
import { motion } from 'framer-motion'
import type { WizardStepProps } from '@edforge/wizard'
import {
  GENDER_OPTIONS,
  SUFFIX_OPTIONS,
  generateStaffUniqueId,
} from '../staff-wizard.utils'
import { AnimatedInput, AnimatedSelect, AnimatedCheckbox } from './shared'

export function PersonalInfoStep({ data, updateData, errors, clearError }: WizardStepProps) {
  const [idWasAutoGenerated, setIdWasAutoGenerated] = useState(true)

  const handleChange = (field: string) => (
    e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>,
  ) => {
    updateData({ [field]: e.target.value })
    clearError(field)
  }

  // Auto-generate staffUniqueId from name
  useEffect(() => {
    const firstName = data.firstName as string
    const lastName = data.lastSurname as string
    if (firstName && lastName && idWasAutoGenerated) {
      updateData({ staffUniqueId: generateStaffUniqueId(firstName, lastName) })
    }
  }, [data.firstName, data.lastSurname]) // eslint-disable-line react-hooks/exhaustive-deps

  return (
    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-5">
      {/* Name Fields */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <AnimatedInput
          label="First Name"
          required
          placeholder="e.g., John"
          autoComplete="given-name"
          value={(data.firstName as string) || ''}
          onChange={handleChange('firstName')}
          error={errors.firstName}
        />
        <AnimatedInput
          label="Last Name"
          required
          placeholder="e.g., Smith"
          autoComplete="family-name"
          value={(data.lastSurname as string) || ''}
          onChange={handleChange('lastSurname')}
          error={errors.lastSurname}
        />
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <AnimatedInput
          label="Middle Name"
          placeholder="e.g., Michael"
          autoComplete="additional-name"
          value={(data.middleName as string) || ''}
          onChange={handleChange('middleName')}
        />
        <AnimatedInput
          label="Maiden Name"
          placeholder="e.g., Johnson"
          value={(data.maidenName as string) || ''}
          onChange={handleChange('maidenName')}
        />
        <AnimatedSelect
          label="Suffix"
          value={(data.generationCodeSuffix as string) || ''}
          onChange={handleChange('generationCodeSuffix')}
          options={SUFFIX_OPTIONS}
        />
      </div>

      {/* Staff ID */}
      <AnimatedInput
        label="Staff Unique ID"
        required
        placeholder="e.g., JS4821"
        value={(data.staffUniqueId as string) || ''}
        onChange={(e) => {
          setIdWasAutoGenerated(false)
          updateData({ staffUniqueId: e.target.value.toUpperCase() })
          clearError('staffUniqueId')
        }}
        error={errors.staffUniqueId}
        helpText="Employee number or state ID. Auto-generated from name, but you can override."
        className="font-mono uppercase"
      />

      {/* Demographics */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <AnimatedInput
          label="Date of Birth"
          type="date"
          value={(data.birthDate as string) || ''}
          onChange={handleChange('birthDate')}
          error={errors.birthDate}
        />
        <AnimatedSelect
          label="Gender"
          value={(data.gender as string) || ''}
          onChange={handleChange('gender')}
          options={GENDER_OPTIONS}
        />
      </div>

      <AnimatedCheckbox
        label="Hispanic/Latino Ethnicity"
        checked={data.hispanicLatinoEthnicity === true}
        onChange={(checked) => updateData({ hispanicLatinoEthnicity: checked })}
        helpText="Ed-Fi compliance field"
      />
    </motion.div>
  )
}
