/**
 * ReportCardPrint — browser-print / Save-as-PDF for a single ResultCard.
 *
 * Layer 5 (presentation) starter: renders a self-contained, print-optimized
 * report-card document in a new window and triggers the browser print dialog
 * (which doubles as "Save as PDF"). Self-contained HTML + inline print CSS so
 * it doesn't depend on the SPA's Tailwind/theme being available in the print
 * window, and so we never have to fight the shell's `@media print` rules.
 *
 * Scheme-aware (mirrors ResultCardsDrawer): a card with `result` set is the
 * Division scheme (PABSON terminal) → Full/Pass/Obtained/Result columns +
 * Percentage/Division/Result/Position footer; otherwise letter_gpa →
 * Score/Grade/GPA/Pass + Term GPA/Overall. Theory/Practical components render
 * as a sub-line under the subject. Visual layout is intentionally plain — the
 * per-school branded layout is the full Layer 5 epic; this is the functional
 * baseline so operators can produce a physical card today.
 */

import type { ExamResponseDto, ResultCardResponseDto } from '@aibrains/shared-types'
import { getAcademicSubjectLabel, getSubjectAreaLabel } from '../../schemas/course.form'
import { humanizeExamType } from '../../schemas/exam.form'

type CourseScore = ResultCardResponseDto['courseScores'][number]

export interface ReportCardPrintLabels {
  reportCard: string
  progressReport: string
  printSavePdf: string
  printed: string
  subject: string
  full: string
  passMarks: string
  obtained: string
  highestMarks: string
  result: string
  score: string
  grade: string
  gpa: string
  pass: string
  fail: string
  passUpper: string
  failUpper: string
  absent: string
  total: string
  percentage: string
  division: string
  position: string
  termGpa: string
  overall: string
  conduct: string
  classTeacherRemark: string
  classTeacher: string
  principal: string
  parentGuardian: string
  generatedBy: string
  published: string
  draftNotPublished: string
  gradePrefix: string
  emisPrefix: string
  lang: string
}

interface ReportCardPrintOptions {
  labels?: Partial<ReportCardPrintLabels>
  printedOn?: string
  examTypeLabel?: string
}

const DEFAULT_PRINT_LABELS: ReportCardPrintLabels = {
  reportCard: 'Report Card',
  progressReport: 'Progress Report',
  printSavePdf: 'Print / Save as PDF',
  printed: 'Printed',
  subject: 'Subject',
  full: 'Full',
  passMarks: 'Pass',
  obtained: 'Obt.',
  highestMarks: 'H.M.',
  result: 'Result',
  score: 'Score',
  grade: 'Grade',
  gpa: 'GPA',
  pass: 'Pass',
  fail: 'Fail',
  passUpper: 'PASS',
  failUpper: 'FAIL',
  absent: 'AB',
  total: 'Total',
  percentage: 'Percentage',
  division: 'Division',
  position: 'Position',
  termGpa: 'Term GPA',
  overall: 'Overall',
  conduct: 'Conduct',
  classTeacherRemark: 'Class-Teacher Remark',
  classTeacher: 'Class Teacher',
  principal: 'Principal',
  parentGuardian: 'Parent / Guardian',
  generatedBy: 'Generated by EdForge',
  published: 'Published',
  draftNotPublished: 'Draft (not yet published)',
  gradePrefix: 'Grade',
  emisPrefix: 'EMIS',
  lang: 'en',
}

function esc(value: unknown): string {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

function isDivisionCard(card: ResultCardResponseDto): boolean {
  return card.result != null
}

function subjectLabel(cs: CourseScore): string {
  if (cs.academicSubject) return getAcademicSubjectLabel(cs.academicSubject)
  if (cs.subjectArea) return getSubjectAreaLabel(cs.subjectArea)
  return cs.courseName ?? '—'
}

function componentLine(cs: CourseScore): string {
  if (!cs.components || cs.components.length === 0) return ''
  const parts = cs.components.map((c) => `${esc(c.label ?? c.code)} ${c.obtained}/${c.fullMarks}`)
  return `<div class="components">${parts.join(' &middot; ')}</div>`
}

function passText(cs: CourseScore, division: boolean, labels: ReportCardPrintLabels): string {
  if (cs.notGraded) return `<span class="ab">${esc(labels.absent)}</span>`
  const passed = division ? cs.pass === true : cs.isPassing
  return passed
    ? `<span class="ok">${esc(labels.pass)}</span>`
    : `<span class="fail">${esc(labels.fail)}</span>`
}

function subjectRows(card: ResultCardResponseDto, division: boolean, labels: ReportCardPrintLabels): string {
  const rows = card.courseScores
    .map((cs) => {
      const marks = cs.notGraded ? '—' : `${cs.rawScore} / ${cs.maxMarks}`
      const subject = `${esc(subjectLabel(cs))}${componentLine(cs)}`
      if (division) {
        return `<tr>
          <td class="subj">${subject}</td>
          <td class="num">${cs.maxMarks}</td>
          <td class="num">${cs.passMarks ?? '—'}</td>
          <td class="num">${cs.notGraded ? '—' : cs.rawScore}</td>
          <td class="num">${cs.highestInClass ?? '—'}</td>
          <td class="ctr">${passText(cs, true, labels)}</td>
        </tr>`
      }
      return `<tr>
        <td class="subj">${subject}</td>
        <td class="num">${marks}</td>
        <td class="ctr">${esc(cs.grade)}</td>
        <td class="num">${cs.gpa.toFixed(2)}</td>
        <td class="ctr">${passText(cs, false, labels)}</td>
      </tr>`
    })
    .join('')

  const totalCols = division
    ? `<td class="num">${card.totalMaxMarks}</td><td></td><td class="num">${card.totalScore}</td><td colspan="2"></td>`
    : `<td class="num">${card.totalScore} / ${card.totalMaxMarks}</td><td colspan="3"></td>`
  return `${rows}<tr class="total"><td class="subj">${esc(labels.total)}</td>${totalCols}</tr>`
}

function tableHead(division: boolean, labels: ReportCardPrintLabels): string {
  return division
    ? `<th class="subj">${esc(labels.subject)}</th><th class="num">${esc(labels.full)}</th><th class="num">${esc(labels.passMarks)}</th><th class="num">${esc(labels.obtained)}</th><th class="num">${esc(labels.highestMarks)}</th><th class="ctr">${esc(labels.result)}</th>`
    : `<th class="subj">${esc(labels.subject)}</th><th class="num">${esc(labels.score)}</th><th class="ctr">${esc(labels.grade)}</th><th class="num">${esc(labels.gpa)}</th><th class="ctr">${esc(labels.pass)}</th>`
}

function summaryBlock(card: ResultCardResponseDto, division: boolean, labels: ReportCardPrintLabels): string {
  const cell = (label: string, value: string) =>
    `<div class="sum-cell"><div class="sum-label">${esc(label)}</div><div class="sum-value">${value}</div></div>`
  if (division) {
    const result = card.result === 'pass'
      ? `<span class="ok">${esc(labels.passUpper)}</span>`
      : `<span class="fail">${esc(labels.failUpper)}</span>`
    return [
      card.percentage != null ? cell(labels.percentage, `${card.percentage.toFixed(1)}%`) : '',
      cell(labels.division, esc(card.division ?? '—')),
      cell(labels.result, result),
      cell(labels.position, esc(card.classRank ?? '—')),
    ].join('')
  }
  return [cell(labels.termGpa, card.termGpa.toFixed(2)), cell(labels.overall, esc(card.overallGrade))].join('')
}

function studentName(card: ResultCardResponseDto): string {
  const id = (card as ResultCardResponseDto & { studentIdentity?: { legalName?: string } }).studentIdentity
  return id?.legalName ?? card.studentId
}

function studentMeta(card: ResultCardResponseDto, labels: ReportCardPrintLabels): string {
  const id = (card as ResultCardResponseDto & {
    studentIdentity?: { gradeLevel?: string; emisStudentId?: string }
  }).studentIdentity
  const bits: string[] = []
  if (id?.gradeLevel) bits.push(`${esc(labels.gradePrefix)} ${esc(id.gradeLevel)}`)
  if (id?.emisStudentId) bits.push(`${esc(labels.emisPrefix)} ${esc(id.emisStudentId)}`)
  return bits.join(' &middot; ')
}

export function buildReportCardHtml(
  card: ResultCardResponseDto,
  exam: ExamResponseDto,
  schoolName?: string,
  options: ReportCardPrintOptions = {},
): string {
  const labels = { ...DEFAULT_PRINT_LABELS, ...options.labels }
  const division = isDivisionCard(card)
  const printedOn = options.printedOn ?? new Date().toLocaleDateString()
  const remarkBlock = (label: string, value?: string | null) =>
    `<div class="remark"><span class="remark-label">${esc(label)}:</span> ${esc(value || '—')}</div>`

  return `<!doctype html>
<html lang="${esc(labels.lang)}">
<head>
<meta charset="utf-8" />
<title>${esc(labels.reportCard)} — ${esc(studentName(card))}</title>
<style>
  @page { size: A4; margin: 14mm; }
  * { box-sizing: border-box; }
  body { font-family: -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif; color: #111; margin: 0; }
  .card { max-width: 760px; margin: 0 auto; }
  .head { text-align: center; border-bottom: 2px solid #111; padding-bottom: 8px; margin-bottom: 12px; }
  .school { font-size: 20px; font-weight: 700; }
  .doc { font-size: 13px; color: #333; margin-top: 2px; }
  .exam { font-size: 13px; color: #333; margin-top: 2px; }
  .student { display: flex; justify-content: space-between; align-items: baseline; margin: 10px 0; }
  .student .name { font-size: 15px; font-weight: 600; }
  .student .meta { font-size: 12px; color: #555; }
  table { width: 100%; border-collapse: collapse; font-size: 12.5px; }
  th, td { border: 1px solid #999; padding: 5px 8px; }
  th { background: #f0f0f0; text-align: left; }
  td.num, th.num { text-align: right; }
  td.ctr, th.ctr { text-align: center; }
  td.subj { text-align: left; }
  .components { font-size: 11px; color: #666; margin-top: 2px; }
  tr.total td { font-weight: 700; background: #fafafa; }
  .ok { color: #15803d; font-weight: 600; }
  .fail { color: #b91c1c; font-weight: 600; }
  .ab { color: #b45309; font-weight: 600; }
  .summary { display: flex; gap: 18px; flex-wrap: wrap; margin: 14px 0; }
  .sum-cell { min-width: 90px; }
  .sum-label { font-size: 11px; color: #666; text-transform: uppercase; letter-spacing: .03em; }
  .sum-value { font-size: 16px; font-weight: 700; }
  .remarks { margin-top: 10px; font-size: 12.5px; }
  .remark { margin-top: 4px; }
  .remark-label { font-weight: 600; }
  .signs { display: flex; justify-content: space-between; margin-top: 48px; font-size: 12px; color: #333; }
  .sign { text-align: center; width: 30%; }
  .sign .line { border-top: 1px solid #111; padding-top: 4px; }
  .footer { margin-top: 18px; font-size: 10.5px; color: #888; text-align: center; }
  @media print { .no-print { display: none !important; } }
  .no-print { text-align: center; margin: 12px 0; }
  .no-print button { font-size: 13px; padding: 6px 14px; cursor: pointer; }
</style>
</head>
<body>
  <div class="no-print">
    <button onclick="window.print()">${esc(labels.printSavePdf)}</button>
  </div>
  <div class="card">
    <div class="head">
      <div class="school">${esc(schoolName || labels.reportCard)}</div>
      <div class="doc">${esc(labels.progressReport)}</div>
      <div class="exam">${esc(exam.examName)} &middot; ${esc(options.examTypeLabel ?? humanizeExamType(exam.examType))}</div>
    </div>

    <div class="student">
      <div><div class="name">${esc(studentName(card))}</div><div class="meta">${studentMeta(card, labels)}</div></div>
      <div class="meta">${esc(labels.printed)} ${esc(printedOn)}</div>
    </div>

    <table>
      <thead><tr>${tableHead(division, labels)}</tr></thead>
      <tbody>${subjectRows(card, division, labels)}</tbody>
    </table>

    <div class="summary">${summaryBlock(card, division, labels)}</div>

    <div class="remarks">
      ${remarkBlock(labels.conduct, card.conduct)}
      ${remarkBlock(labels.classTeacherRemark, card.classTeacherRemark)}
    </div>

    <div class="signs">
      <div class="sign"><div class="line">${esc(labels.classTeacher)}</div></div>
      <div class="sign"><div class="line">${esc(labels.principal)}</div></div>
      <div class="sign"><div class="line">${esc(labels.parentGuardian)}</div></div>
    </div>

    <div class="footer">${esc(labels.generatedBy)}${card.status === 'published' ? ` &middot; ${esc(labels.published)}` : ` &middot; ${esc(labels.draftNotPublished)}`}</div>
  </div>
</body>
</html>`
}

/**
 * Open a print-ready report card in a new window and trigger the print dialog.
 * No-op (returns false) if the popup is blocked.
 */
export function openReportCardPrint(
  card: ResultCardResponseDto,
  exam: ExamResponseDto,
  schoolName?: string,
  options?: ReportCardPrintOptions,
): boolean {
  const win = window.open('', '_blank', 'noopener,noreferrer,width=900,height=1100')
  if (!win) return false
  win.document.open()
  win.document.write(buildReportCardHtml(card, exam, schoolName, options))
  win.document.close()
  // Print once the new document has laid out. The window stays open so the
  // operator can cancel / re-print / Save-as-PDF.
  win.onload = () => {
    win.focus()
    win.print()
  }
  return true
}
