/**
 * ResultCardsDrawer — result cards (Ed-Fi ReportCard) for one exam.
 *
 * Master → detail in a single slide-over:
 *   - list view: the exam's generated result cards (one per enrollment),
 *   - detail view: a ReportCard (per-course rows, term GPA, overall grade),
 *     with editable conduct + class-teacher remark while `draft`, and the
 *     terminal publish action.
 *
 * Result cards are generated by the backend when an exam transitions to
 * `closed`; a draft/scheduled exam has none yet.
 */

import { useMemo, useState, useEffect, useRef } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { X, Loader2, ClipboardList, ArrowLeft, CheckCircle2, Lock } from 'lucide-react'
import { UuidBadge } from '@edforge/archetype'
import type { ExamResponseDto, ResultCardResponseDto } from '@aibrains/shared-types'
import {
  useResultCards,
  useUpdateResultCardConduct,
  useUpdateResultCardRemark,
  usePublishResultCard,
} from '../../hooks/useResultCards'
import { getAcademicSubjectLabel } from '../../schemas/course.form'
import { humanizeExamType } from '../../schemas/exam.form'

function gpaClass(gpa: number): string {
  if (gpa >= 3.5) return 'text-emerald-600 dark:text-emerald-400'
  if (gpa >= 3.0) return 'text-blue-600 dark:text-blue-400'
  if (gpa >= 2.0) return 'text-amber-600 dark:text-amber-400'
  return 'text-red-600 dark:text-red-400'
}

function StatusBadge({ status }: { status: ResultCardResponseDto['status'] }) {
  const published = status === 'published'
  return (
    <span
      className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-md text-xs font-medium ${
        published
          ? 'bg-emerald-50 text-emerald-700 dark:bg-emerald-500/20 dark:text-emerald-300'
          : 'bg-gray-100 text-gray-700 dark:bg-gray-500/20 dark:text-gray-300'
      }`}
    >
      {published ? <Lock className="w-3 h-3" /> : null}
      {published ? 'Published' : 'Draft'}
    </span>
  )
}

// ============================================================================
// DETAIL — a single ReportCard
// ============================================================================

function ReportCardDetail({
  card,
  onBack,
  onCardUpdated,
}: {
  card: ResultCardResponseDto
  onBack: () => void
  onCardUpdated: (card: ResultCardResponseDto) => void
}) {
  const isDraft = card.status === 'draft'
  const [conduct, setConduct] = useState(card.conduct ?? '')
  const [remark, setRemark] = useState(card.classTeacherRemark ?? '')

  const conductMutation = useUpdateResultCardConduct()
  const remarkMutation = useUpdateResultCardRemark()
  const publishMutation = usePublishResultCard()

  useEffect(() => {
    setConduct(card.conduct ?? '')
    setRemark(card.classTeacherRemark ?? '')
  }, [card.cardId, card.conduct, card.classTeacherRemark])

  const handlePublish = async () => {
    if (!window.confirm('Publish this result card? Publishing is final and cannot be undone.')) return
    const updated = await publishMutation.mutateAsync({ cardId: card.cardId, enrollmentId: card.enrollmentId })
    onCardUpdated(updated)
  }

  const handleSaveConduct = async () => {
    const updated = await conductMutation.mutateAsync({ cardId: card.cardId, enrollmentId: card.enrollmentId, conduct })
    onCardUpdated(updated)
  }

  const handleSaveRemark = async () => {
    const updated = await remarkMutation.mutateAsync({
      cardId: card.cardId,
      enrollmentId: card.enrollmentId,
      classTeacherRemark: remark,
    })
    onCardUpdated(updated)
  }

  return (
    <div className="flex flex-col flex-1 min-h-0 overflow-hidden">
      <div className="flex-1 overflow-y-auto px-6 py-4 space-y-6">
        <button
          type="button"
          onClick={onBack}
          className="flex items-center gap-1.5 text-sm text-text-tertiary hover:text-text-primary transition-colors"
        >
          <ArrowLeft className="w-4 h-4" />
          All result cards
        </button>

        {/* Summary */}
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div>
            <p className="text-xs text-text-tertiary mb-0.5">Student</p>
            <UuidBadge value={card.studentId} />
          </div>
          <div className="flex items-center gap-4">
            <div className="text-right">
              <p className="text-xs text-text-tertiary">Term GPA</p>
              <p className={`text-lg font-semibold ${gpaClass(card.termGpa)}`}>{card.termGpa.toFixed(2)}</p>
            </div>
            <div className="text-right">
              <p className="text-xs text-text-tertiary">Overall</p>
              <p className="text-lg font-semibold text-text-primary">{card.overallGrade}</p>
            </div>
            <StatusBadge status={card.status} />
          </div>
        </div>

        {/* Per-course rows (Ed-Fi ReportCardGrade) */}
        <div className="overflow-hidden rounded-xl border border-border-secondary">
          <table className="w-full text-sm">
            <thead>
              <tr className="bg-surface-secondary text-left text-text-tertiary">
                <th className="px-3 py-2 font-medium">Subject</th>
                <th className="px-3 py-2 font-medium text-right">Score</th>
                <th className="px-3 py-2 font-medium text-center">Grade</th>
                <th className="px-3 py-2 font-medium text-right">GPA</th>
                <th className="px-3 py-2 font-medium text-center">Pass</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border-secondary">
              {card.courseScores.map((cs, i) => (
                <tr key={`${cs.academicSubject}-${i}`} className="bg-surface-primary">
                  <td className="px-3 py-2 text-text-primary">{getAcademicSubjectLabel(cs.academicSubject)}</td>
                  <td className="px-3 py-2 text-right text-text-secondary">
                    {cs.rawScore} / {cs.maxMarks}
                  </td>
                  <td className="px-3 py-2 text-center font-medium text-text-primary">{cs.grade}</td>
                  <td className={`px-3 py-2 text-right ${gpaClass(cs.gpa)}`}>{cs.gpa.toFixed(2)}</td>
                  <td className="px-3 py-2 text-center">
                    {cs.isPassing ? (
                      <CheckCircle2 className="w-4 h-4 text-emerald-500 inline" />
                    ) : (
                      <span className="text-red-500 text-xs font-medium">NG</span>
                    )}
                  </td>
                </tr>
              ))}
              <tr className="bg-surface-secondary/60 font-medium">
                <td className="px-3 py-2 text-text-primary">Total</td>
                <td className="px-3 py-2 text-right text-text-primary">
                  {card.totalScore} / {card.totalMaxMarks}
                </td>
                <td colSpan={3} />
              </tr>
            </tbody>
          </table>
        </div>

        {/* Conduct */}
        <div>
          <label className="block text-sm font-medium text-text-primary mb-1.5">Conduct</label>
          {isDraft ? (
            <>
              <textarea
                value={conduct}
                onChange={(e) => setConduct(e.target.value)}
                rows={2}
                placeholder="Conduct note…"
                className="w-full px-3 py-2 text-sm bg-surface-primary border border-border-primary rounded-lg text-text-primary placeholder:text-text-tertiary focus:outline-none focus:ring-2 focus:ring-purple-500/20 focus:border-purple-500"
              />
              <button
                type="button"
                onClick={handleSaveConduct}
                disabled={conductMutation.isPending || conduct === (card.conduct ?? '')}
                className="mt-1.5 text-xs font-medium text-purple-600 hover:text-purple-700 disabled:opacity-50"
              >
                {conductMutation.isPending ? 'Saving…' : 'Save conduct'}
              </button>
            </>
          ) : (
            <p className="text-sm text-text-secondary">{card.conduct || '—'}</p>
          )}
        </div>

        {/* Class-teacher remark */}
        <div>
          <label className="block text-sm font-medium text-text-primary mb-1.5">Class-Teacher Remark</label>
          {isDraft ? (
            <>
              <textarea
                value={remark}
                onChange={(e) => setRemark(e.target.value)}
                rows={2}
                placeholder="Class-teacher remark…"
                className="w-full px-3 py-2 text-sm bg-surface-primary border border-border-primary rounded-lg text-text-primary placeholder:text-text-tertiary focus:outline-none focus:ring-2 focus:ring-purple-500/20 focus:border-purple-500"
              />
              <button
                type="button"
                onClick={handleSaveRemark}
                disabled={remarkMutation.isPending || remark === (card.classTeacherRemark ?? '')}
                className="mt-1.5 text-xs font-medium text-purple-600 hover:text-purple-700 disabled:opacity-50"
              >
                {remarkMutation.isPending ? 'Saving…' : 'Save remark'}
              </button>
            </>
          ) : (
            <p className="text-sm text-text-secondary">{card.classTeacherRemark || '—'}</p>
          )}
        </div>
      </div>

      {/* Footer — publish */}
      <div className="shrink-0 flex items-center justify-between gap-3 px-6 py-4 border-t border-border-secondary bg-surface-secondary/50">
        <span className="text-xs text-text-tertiary">
          {card.status === 'published' ? 'Published — read only' : 'Draft — review then publish'}
        </span>
        {isDraft && (
          <button
            type="button"
            onClick={handlePublish}
            disabled={publishMutation.isPending}
            className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-white bg-emerald-600 rounded-lg hover:bg-emerald-700 transition-colors disabled:opacity-50"
          >
            {publishMutation.isPending ? <Loader2 className="w-4 h-4 animate-spin" /> : <Lock className="w-4 h-4" />}
            Publish
          </button>
        )}
      </div>
    </div>
  )
}

// ============================================================================
// LIST — the exam's result cards
// ============================================================================

function ResultCardList({
  examId,
  onSelect,
}: {
  examId: string
  onSelect: (card: ResultCardResponseDto) => void
}) {
  const { data, isLoading } = useResultCards({ examId })
  const cards = useMemo(() => data?.items ?? [], [data])

  if (isLoading) {
    return (
      <div className="px-6 py-4 space-y-3">
        {Array.from({ length: 5 }).map((_, i) => (
          <div key={i} className="h-12 bg-surface-secondary rounded-lg animate-pulse" />
        ))}
      </div>
    )
  }

  if (cards.length === 0) {
    return (
      <div className="px-6 py-12 text-center">
        <ClipboardList className="w-10 h-10 mx-auto text-text-tertiary mb-3" />
        <h4 className="text-base font-medium text-text-primary mb-1">No Result Cards Yet</h4>
        <p className="text-sm text-text-secondary max-w-sm mx-auto">
          Result cards are generated automatically once this exam is closed. Close the exam after all scores are entered.
        </p>
      </div>
    )
  }

  return (
    <div className="flex-1 overflow-y-auto px-6 py-4">
      <div className="overflow-hidden rounded-xl border border-border-secondary">
        <table className="w-full text-sm">
          <thead>
            <tr className="bg-surface-secondary text-left text-text-tertiary">
              <th className="px-3 py-2 font-medium">Student</th>
              <th className="px-3 py-2 font-medium text-right">Total</th>
              <th className="px-3 py-2 font-medium text-right">GPA</th>
              <th className="px-3 py-2 font-medium text-center">Grade</th>
              <th className="px-3 py-2 font-medium text-center">Status</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-border-secondary">
            {cards.map((card) => (
              <tr
                key={card.cardId}
                onClick={() => onSelect(card)}
                className="bg-surface-primary hover:bg-surface-secondary/60 transition-colors cursor-pointer"
              >
                <td className="px-3 py-2"><UuidBadge value={card.studentId} /></td>
                <td className="px-3 py-2 text-right text-text-secondary">
                  {card.totalScore}/{card.totalMaxMarks}
                </td>
                <td className={`px-3 py-2 text-right ${gpaClass(card.termGpa)}`}>{card.termGpa.toFixed(2)}</td>
                <td className="px-3 py-2 text-center font-medium text-text-primary">{card.overallGrade}</td>
                <td className="px-3 py-2 text-center">
                  <StatusBadge status={card.status} />
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  )
}

// ============================================================================
// DRAWER
// ============================================================================

interface ResultCardsDrawerProps {
  open: boolean
  onClose: () => void
  exam: ExamResponseDto | null
}

export function ResultCardsDrawer({ open, onClose, exam }: ResultCardsDrawerProps) {
  const [selectedCard, setSelectedCard] = useState<ResultCardResponseDto | null>(null)
  const closeButtonRef = useRef<HTMLButtonElement>(null)
  const prevFocusedRef = useRef<HTMLElement | null>(null)

  useEffect(() => {
    if (!open) setSelectedCard(null)
  }, [open])

  // Modal a11y: trap entry focus on open, ESC to close, restore focus on close.
  useEffect(() => {
    if (!open) return
    prevFocusedRef.current = document.activeElement as HTMLElement | null
    closeButtonRef.current?.focus()
    const handleEscape = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose()
    }
    document.addEventListener('keydown', handleEscape)
    return () => {
      document.removeEventListener('keydown', handleEscape)
      prevFocusedRef.current?.focus()
    }
  }, [open, onClose])

  return (
    <AnimatePresence>
      {open && exam && (
        <div className="fixed inset-0 z-50" role="dialog" aria-modal="true" aria-labelledby="result-cards-title">
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.2 }}
            className="fixed inset-0 bg-black/30 backdrop-blur-sm"
            onClick={(e) => {
              if (e.target === e.currentTarget) onClose()
            }}
            aria-hidden="true"
          />
          <div className="fixed inset-y-0 right-0 flex max-w-full pl-10">
            <motion.div
              initial={{ x: '100%' }}
              animate={{ x: 0 }}
              exit={{ x: '100%' }}
              transition={{ type: 'spring', damping: 30, stiffness: 300 }}
              className="w-screen max-w-2xl h-full"
            >
              <div className="flex h-full flex-col bg-surface-primary shadow-xl border-l border-border-secondary">
                <div className="flex items-center justify-between px-6 py-4 border-b border-border-secondary">
                  <div className="flex items-center gap-3 min-w-0">
                    <div className="p-2 rounded-lg bg-gradient-to-br from-emerald-500/20 to-teal-500/20 flex-shrink-0">
                      <ClipboardList className="w-5 h-5 text-emerald-600 dark:text-emerald-400" />
                    </div>
                    <div className="min-w-0">
                      <h2 id="result-cards-title" className="text-lg font-semibold text-text-primary truncate">
                        Result Cards
                      </h2>
                      <p className="text-xs text-text-tertiary truncate">
                        {exam.examName} · {humanizeExamType(exam.examType)}
                      </p>
                    </div>
                  </div>
                  <button
                    type="button"
                    ref={closeButtonRef}
                    onClick={onClose}
                    className="p-1.5 rounded-lg text-text-tertiary hover:text-text-primary hover:bg-surface-secondary transition-colors flex-shrink-0"
                    aria-label="Close drawer"
                  >
                    <X className="w-5 h-5" />
                  </button>
                </div>

                {selectedCard ? (
                  <ReportCardDetail
                    card={selectedCard}
                    onBack={() => setSelectedCard(null)}
                    onCardUpdated={setSelectedCard}
                  />
                ) : (
                  <ResultCardList examId={exam.examId} onSelect={setSelectedCard} />
                )}
              </div>
            </motion.div>
          </div>
        </div>
      )}
    </AnimatePresence>
  )
}
