/**
 * ResultCardsDrawer — result cards (Ed-Fi ReportCard) for one exam.
 *
 * Master → detail in a single slide-over:
 *   - list view: the exam's generated result cards (one per enrollment),
 *   - detail view: a ReportCard (per-course rows, term GPA, overall grade),
 *     with editable conduct + class-teacher remark while `draft`, and the
 *     terminal publish action.
 *
 * Result cards are generated by the backend when an exam transitions to
 * `closed`; a draft/scheduled exam has none yet.
 */

import { useMemo, useState, useEffect, useRef } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { X, Loader2, ClipboardList, ArrowLeft, CheckCircle2, Lock, Printer, AlertCircle } from 'lucide-react'
import { UuidBadge } from '@edforge/archetype'
import { Avatar } from '@edforge/ui'
import type { ExamResponseDto, ResultCardResponseDto } from '@aibrains/shared-types'
import {
  useResultCards,
  useUpdateResultCardConduct,
  useUpdateResultCardRemark,
  usePublishResultCard,
} from '../../hooks/useResultCards'
import { getAcademicSubjectLabel, getSubjectAreaLabel } from '../../schemas/course.form'
import { humanizeExamType } from '../../schemas/exam.form'
import { useSchoolProfile } from '../../hooks/useSchool'
import { openReportCardPrint } from './ReportCardPrint'

function gpaClass(gpa: number): string {
  if (gpa >= 3.5) return 'text-[rgb(var(--state-success-fg))]'
  if (gpa >= 3.0) return 'text-[rgb(var(--state-info-fg))]'
  if (gpa >= 2.0) return 'text-[rgb(var(--state-warning-fg))]'
  return 'text-[rgb(var(--state-danger-fg))]'
}

// P1.5a/b — scheme is data, not config: a `result` (pass/fail) on the card means
// the Division scheme produced it (PABSON terminal). letter_gpa cards leave
// `result`/`division` unset and carry the letter `overallGrade` + `termGpa`.
function isDivisionCard(card: ResultCardResponseDto): boolean {
  return card.result != null
}

type CourseScore = ResultCardResponseDto['courseScores'][number]

/** Per-subject outcome cell: Absent (AB) is a distinct non-failing state (P1b). */
function CoursePassCell({ cs, division }: { cs: CourseScore; division: boolean }) {
  if (cs.notGraded) {
    return <span className="text-[rgb(var(--state-warning-fg))] text-xs font-medium" title="Absent / Not graded">AB</span>
  }
  const passed = division ? cs.pass === true : cs.isPassing
  return passed ? (
    <CheckCircle2 className="w-4 h-4 text-[rgb(var(--state-success-fg))] inline" />
  ) : (
    <span className="text-[rgb(var(--state-danger-fg))] text-xs font-medium">Fail</span>
  )
}

/** Theory/Practical (or custom) breakdown shown under the subject name. */
function ComponentBreakdown({ cs }: { cs: CourseScore }) {
  if (!cs.components || cs.components.length === 0) return null
  return (
    <span className="block text-xs text-text-tertiary">
      {cs.components
        .map((c) => `${c.label ?? c.code} ${c.obtained}/${c.fullMarks}`)
        .join(' · ')}
    </span>
  )
}

// RC-UX.2: the frozen identity snapshot RC-UX.1 denormalizes onto the card. Typed
// here as a local bridge until @aibrains/shared-types is published with the field;
// the runtime data is present once the backend (RC-UX.1) is deployed.
interface ResultCardStudentIdentity {
  legalName: string
  preferredName?: string
  gradeLevel?: string
  emisStudentId?: string
  photoUrl?: string
}

function cardIdentity(card: ResultCardResponseDto): ResultCardStudentIdentity | undefined {
  return (card as ResultCardResponseDto & { studentIdentity?: ResultCardStudentIdentity }).studentIdentity
}

/** Roster student cell: avatar + name + grade, falling back to the id badge. */
function StudentCell({ card, size = 'sm' }: { card: ResultCardResponseDto; size?: 'sm' | 'md' }) {
  const id = cardIdentity(card)
  if (!id) return <UuidBadge value={card.studentId} />
  return (
    <div className="flex items-center gap-2.5 min-w-0">
      <Avatar name={id.legalName} src={id.photoUrl} size={size} className="flex-shrink-0" />
      <div className="min-w-0">
        <p className="text-sm font-medium text-text-primary truncate">
          {id.legalName}
          {id.preferredName ? <span className="text-text-tertiary font-normal"> ({id.preferredName})</span> : null}
        </p>
        {(id.gradeLevel || id.emisStudentId) && (
          <p className="text-xs text-text-tertiary truncate">
            {id.gradeLevel ? `Grade ${id.gradeLevel}` : ''}
            {id.gradeLevel && id.emisStudentId ? ' · ' : ''}
            {id.emisStudentId ? `EMIS ${id.emisStudentId}` : ''}
          </p>
        )}
      </div>
    </div>
  )
}

function StatusBadge({ status }: { status: ResultCardResponseDto['status'] }) {
  const published = status === 'published'
  return (
    <span
      className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-md text-xs font-medium ${
        published
          ? 'bg-[rgb(var(--state-success-bg)/0.18)] text-[rgb(var(--state-success-fg))] dark:bg-[rgb(var(--state-success-bg)/0.18)]0/20 '
          : 'bg-[rgb(var(--surface-tertiary))] text-[rgb(var(--text-secondary))] bg-[rgb(var(--surface-tertiary))] '
      }`}
    >
      {published ? <Lock className="w-3 h-3" /> : null}
      {published ? 'Published' : 'Draft'}
    </span>
  )
}

// ============================================================================
// DETAIL — a single ReportCard
// ============================================================================

function ReportCardDetail({
  card,
  exam,
  schoolName,
  onBack,
  onCardUpdated,
}: {
  card: ResultCardResponseDto
  exam: ExamResponseDto
  schoolName?: string
  onBack: () => void
  onCardUpdated: (card: ResultCardResponseDto) => void
}) {
  const isDraft = card.status === 'draft'
  const division = isDivisionCard(card)
  const [conduct, setConduct] = useState(card.conduct ?? '')
  const [remark, setRemark] = useState(card.classTeacherRemark ?? '')

  const conductMutation = useUpdateResultCardConduct()
  const remarkMutation = useUpdateResultCardRemark()
  const publishMutation = usePublishResultCard()

  useEffect(() => {
    setConduct(card.conduct ?? '')
    setRemark(card.classTeacherRemark ?? '')
  }, [card.cardId, card.conduct, card.classTeacherRemark])

  const handlePublish = async () => {
    if (!window.confirm('Publish this result card? Publishing is final and cannot be undone.')) return
    const updated = await publishMutation.mutateAsync({ cardId: card.cardId, enrollmentId: card.enrollmentId })
    onCardUpdated(updated)
  }

  const handleSaveConduct = async () => {
    const updated = await conductMutation.mutateAsync({ cardId: card.cardId, enrollmentId: card.enrollmentId, conduct })
    onCardUpdated(updated)
  }

  const handleSaveRemark = async () => {
    const updated = await remarkMutation.mutateAsync({
      cardId: card.cardId,
      enrollmentId: card.enrollmentId,
      classTeacherRemark: remark,
    })
    onCardUpdated(updated)
  }

  return (
    <div className="flex flex-col flex-1 min-h-0 overflow-hidden">
      <div className="flex-1 overflow-y-auto px-6 py-4 space-y-6">
        <button
          type="button"
          onClick={onBack}
          className="flex items-center gap-1.5 text-sm text-text-tertiary hover:text-text-primary transition-colors"
        >
          <ArrowLeft className="w-4 h-4" />
          All result cards
        </button>

        {/* Summary — Division scheme shows %/Division/Result/Position; letter_gpa shows GPA/Overall */}
        <div className="flex flex-wrap items-center justify-between gap-3">
          <StudentCell card={card} size="md" />
          <div className="flex items-center gap-4">
            {isDivisionCard(card) ? (
              <>
                {card.percentage != null && (
                  <div className="text-right">
                    <p className="text-xs text-text-tertiary">Percentage</p>
                    <p className="text-lg font-semibold text-text-primary">{card.percentage.toFixed(1)}%</p>
                  </div>
                )}
                <div className="text-right">
                  <p className="text-xs text-text-tertiary">Division</p>
                  <p className="text-lg font-semibold text-text-primary">{card.division ?? '—'}</p>
                </div>
                <div className="text-right">
                  <p className="text-xs text-text-tertiary">Result</p>
                  <p
                    className={`text-lg font-semibold ${
                      card.result === 'pass'
                        ? 'text-[rgb(var(--state-success-fg))]'
                        : 'text-[rgb(var(--state-danger-fg))]'
                    }`}
                  >
                    {card.result === 'pass' ? 'PASS' : 'FAIL'}
                  </p>
                </div>
                <div className="text-right">
                  <p className="text-xs text-text-tertiary">Position</p>
                  <p className="text-lg font-semibold text-text-primary">{card.classRank ?? '—'}</p>
                </div>
              </>
            ) : (
              <>
                <div className="text-right">
                  <p className="text-xs text-text-tertiary">Term GPA</p>
                  <p className={`text-lg font-semibold ${gpaClass(card.termGpa)}`}>{card.termGpa.toFixed(2)}</p>
                </div>
                <div className="text-right">
                  <p className="text-xs text-text-tertiary">Overall</p>
                  <p className="text-lg font-semibold text-text-primary">{card.overallGrade}</p>
                </div>
              </>
            )}
            <StatusBadge status={card.status} />
          </div>
        </div>

        {/* Per-course rows (Ed-Fi ReportCardGrade) */}
        <div className="overflow-hidden rounded-xl border border-border-secondary">
          <table className="w-full text-sm">
            <thead>
              <tr className="bg-surface-secondary text-left text-text-tertiary">
                <th className="px-3 py-2 font-medium">Subject</th>
                {division ? (
                  <>
                    <th className="px-3 py-2 font-medium text-right">Marks</th>
                    <th className="px-3 py-2 font-medium text-right">Pass M.</th>
                    <th className="px-3 py-2 font-medium text-right">H.M.</th>
                    <th className="px-3 py-2 font-medium text-center">Result</th>
                  </>
                ) : (
                  <>
                    <th className="px-3 py-2 font-medium text-right">Score</th>
                    <th className="px-3 py-2 font-medium text-center">Grade</th>
                    <th className="px-3 py-2 font-medium text-right">GPA</th>
                    <th className="px-3 py-2 font-medium text-center">Pass</th>
                  </>
                )}
              </tr>
            </thead>
            <tbody className="divide-y divide-border-secondary">
              {card.courseScores.map((cs, i) => (
                <tr key={`${cs.examCourseId}-${i}`} className="bg-surface-primary">
                  <td className="px-3 py-2 text-text-primary">
                    {cs.academicSubject
                      ? getAcademicSubjectLabel(cs.academicSubject)
                      : cs.subjectArea
                        ? getSubjectAreaLabel(cs.subjectArea)
                        : cs.courseName ?? '—'}
                    <ComponentBreakdown cs={cs} />
                  </td>
                  {division ? (
                    <>
                      <td className="px-3 py-2 text-right text-text-secondary">
                        {cs.notGraded ? '—' : `${cs.rawScore} / ${cs.maxMarks}`}
                      </td>
                      <td className="px-3 py-2 text-right text-text-tertiary">{cs.passMarks ?? '—'}</td>
                      <td className="px-3 py-2 text-right text-text-tertiary">{cs.highestInClass ?? '—'}</td>
                      <td className="px-3 py-2 text-center"><CoursePassCell cs={cs} division /></td>
                    </>
                  ) : (
                    <>
                      <td className="px-3 py-2 text-right text-text-secondary">
                        {cs.notGraded ? '—' : `${cs.rawScore} / ${cs.maxMarks}`}
                      </td>
                      <td className="px-3 py-2 text-center font-medium text-text-primary">{cs.grade}</td>
                      <td className={`px-3 py-2 text-right ${gpaClass(cs.gpa)}`}>{cs.gpa.toFixed(2)}</td>
                      <td className="px-3 py-2 text-center"><CoursePassCell cs={cs} division={false} /></td>
                    </>
                  )}
                </tr>
              ))}
              <tr className="bg-surface-secondary/60 font-medium">
                <td className="px-3 py-2 text-text-primary">Total</td>
                <td className="px-3 py-2 text-right text-text-primary">
                  {card.totalScore} / {card.totalMaxMarks}
                </td>
                <td colSpan={3} />
              </tr>
            </tbody>
          </table>
        </div>

        {/* Conduct */}
        <div>
          <label className="block text-sm font-medium text-text-primary mb-1.5">Conduct</label>
          {isDraft ? (
            <>
              <textarea
                value={conduct}
                onChange={(e) => setConduct(e.target.value)}
                rows={2}
                placeholder="Conduct note…"
                className="w-full px-3 py-2 text-sm bg-surface-primary border border-border-primary rounded-lg text-text-primary placeholder:text-text-tertiary focus:outline-none focus:ring-2 focus:ring-[rgb(var(--border-focus)/0.35)] focus:border-[rgb(var(--border-focus))]"
              />
              <button
                type="button"
                onClick={handleSaveConduct}
                disabled={conductMutation.isPending || conduct === (card.conduct ?? '')}
                className="mt-1.5 text-xs font-medium text-[rgb(var(--state-info-fg))] hover:text-[rgb(var(--text-primary))] disabled:opacity-50"
              >
                {conductMutation.isPending ? 'Saving…' : 'Save conduct'}
              </button>
            </>
          ) : (
            <p className="text-sm text-text-secondary">{card.conduct || '—'}</p>
          )}
        </div>

        {/* Class-teacher remark */}
        <div>
          <label className="block text-sm font-medium text-text-primary mb-1.5">Class-Teacher Remark</label>
          {isDraft ? (
            <>
              <textarea
                value={remark}
                onChange={(e) => setRemark(e.target.value)}
                rows={2}
                placeholder="Class-teacher remark…"
                className="w-full px-3 py-2 text-sm bg-surface-primary border border-border-primary rounded-lg text-text-primary placeholder:text-text-tertiary focus:outline-none focus:ring-2 focus:ring-[rgb(var(--border-focus)/0.35)] focus:border-[rgb(var(--border-focus))]"
              />
              <button
                type="button"
                onClick={handleSaveRemark}
                disabled={remarkMutation.isPending || remark === (card.classTeacherRemark ?? '')}
                className="mt-1.5 text-xs font-medium text-[rgb(var(--state-info-fg))] hover:text-[rgb(var(--text-primary))] disabled:opacity-50"
              >
                {remarkMutation.isPending ? 'Saving…' : 'Save remark'}
              </button>
            </>
          ) : (
            <p className="text-sm text-text-secondary">{card.classTeacherRemark || '—'}</p>
          )}
        </div>
      </div>

      {/* Footer — print + publish */}
      <div className="shrink-0 flex items-center justify-between gap-3 px-6 py-4 border-t border-border-secondary bg-surface-secondary/50">
        <span className="text-xs text-text-tertiary">
          {card.status === 'published' ? 'Published — read only' : 'Draft — review then publish'}
        </span>
        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={() => openReportCardPrint(card, exam, schoolName)}
            className="flex items-center gap-2 px-3 py-2 text-sm font-medium text-text-secondary border border-border-secondary rounded-lg hover:bg-surface-secondary transition-colors"
          >
            <Printer className="w-4 h-4" />
            Print / PDF
          </button>
          {isDraft && (
            <button
              type="button"
              onClick={handlePublish}
              disabled={publishMutation.isPending}
              className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-[rgb(var(--action-primary-fg))] bg-[rgb(var(--state-success-fg))] rounded-lg hover:brightness-95 transition-colors disabled:opacity-50"
            >
              {publishMutation.isPending ? <Loader2 className="w-4 h-4 animate-spin" /> : <Lock className="w-4 h-4" />}
              Publish
            </button>
          )}
        </div>
      </div>
    </div>
  )
}

// ============================================================================
// LIST — the exam's result cards
// ============================================================================

function ResultCardList({
  exam,
  onSelect,
}: {
  exam: ExamResponseDto
  onSelect: (card: ResultCardResponseDto) => void
}) {
  const { data, isLoading } = useResultCards({ examId: exam.examId })
  const cards = useMemo(() => data?.items ?? [], [data])
  // One exam → one grading scheme; key the columns off the cards.
  const division = useMemo(() => cards.some(isDivisionCard), [cards])

  if (isLoading) {
    return (
      <div className="px-6 py-4 space-y-3">
        {Array.from({ length: 5 }).map((_, i) => (
          <div key={i} className="h-12 bg-surface-secondary rounded-lg animate-pulse" />
        ))}
      </div>
    )
  }

  if (cards.length === 0) {
    // P1c — reflect the generation lifecycle so a just-closed exam isn't a
    // silent "nothing here". The exam carries resultGenerationStatus; the
    // detail query polls while pending, so this resolves on its own.
    const gen = exam.resultGenerationStatus
    if (exam.status === 'closed' && gen === 'pending') {
      return (
        <div className="px-6 py-12 text-center">
          <Loader2 className="w-10 h-10 mx-auto text-amber-500 mb-3 animate-spin" />
          <h4 className="text-base font-medium text-text-primary mb-1">Generating result cards…</h4>
          <p className="text-sm text-text-secondary max-w-sm mx-auto">
            This usually takes a few seconds. The list updates automatically when they&apos;re ready.
          </p>
        </div>
      )
    }
    if (exam.status === 'closed' && gen === 'failed') {
      return (
        <div className="px-6 py-12 text-center">
          <AlertCircle className="w-10 h-10 mx-auto text-[rgb(var(--state-danger-fg))] mb-3" />
          <h4 className="text-base font-medium text-text-primary mb-1">Result generation failed</h4>
          <p className="text-sm text-text-secondary max-w-sm mx-auto">
            {exam.lastGenerationError
              ? exam.lastGenerationError
              : 'Something went wrong generating the result cards. Re-opening and re-closing the exam will retry.'}
          </p>
        </div>
      )
    }
    return (
      <div className="px-6 py-12 text-center">
        <ClipboardList className="w-10 h-10 mx-auto text-text-tertiary mb-3" />
        <h4 className="text-base font-medium text-text-primary mb-1">No Result Cards Yet</h4>
        <p className="text-sm text-text-secondary max-w-sm mx-auto">
          Result cards are generated automatically once this exam is closed. Close the exam after all scores are entered.
        </p>
      </div>
    )
  }

  return (
    <div className="flex-1 overflow-y-auto px-6 py-4">
      <div className="overflow-hidden rounded-xl border border-border-secondary">
        <table className="w-full text-sm">
          <thead>
            <tr className="bg-surface-secondary text-left text-text-tertiary">
              <th className="px-3 py-2 font-medium">Student</th>
              <th className="px-3 py-2 font-medium text-right">Total</th>
              {division ? (
                <>
                  <th className="px-3 py-2 font-medium text-right">%</th>
                  <th className="px-3 py-2 font-medium text-center">Division</th>
                  <th className="px-3 py-2 font-medium text-center">Result</th>
                </>
              ) : (
                <>
                  <th className="px-3 py-2 font-medium text-right">GPA</th>
                  <th className="px-3 py-2 font-medium text-center">Grade</th>
                </>
              )}
              <th className="px-3 py-2 font-medium text-center">Status</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-border-secondary">
            {cards.map((card) => (
              <tr
                key={card.cardId}
                onClick={() => onSelect(card)}
                onKeyDown={(e) => {
                  if (e.key === 'Enter' || e.key === ' ') {
                    e.preventDefault()
                    onSelect(card)
                  }
                }}
                tabIndex={0}
                className="bg-surface-primary hover:bg-surface-secondary/60 transition-colors cursor-pointer"
              >
                <td className="px-3 py-2"><StudentCell card={card} /></td>
                <td className="px-3 py-2 text-right text-text-secondary">
                  {card.totalScore}/{card.totalMaxMarks}
                </td>
                {division ? (
                  <>
                    <td className="px-3 py-2 text-right text-text-secondary">
                      {card.percentage != null ? `${card.percentage.toFixed(1)}%` : '—'}
                    </td>
                    <td className="px-3 py-2 text-center text-text-primary">{card.division ?? '—'}</td>
                    <td className="px-3 py-2 text-center">
                      <span
                        className={`text-xs font-semibold ${
                          card.result === 'pass'
                            ? 'text-[rgb(var(--state-success-fg))]'
                            : 'text-[rgb(var(--state-danger-fg))]'
                        }`}
                      >
                        {card.result === 'pass' ? 'PASS' : 'FAIL'}
                      </span>
                    </td>
                  </>
                ) : (
                  <>
                    <td className={`px-3 py-2 text-right ${gpaClass(card.termGpa)}`}>{card.termGpa.toFixed(2)}</td>
                    <td className="px-3 py-2 text-center font-medium text-text-primary">{card.overallGrade}</td>
                  </>
                )}
                <td className="px-3 py-2 text-center">
                  <StatusBadge status={card.status} />
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  )
}

// ============================================================================
// DRAWER
// ============================================================================

interface ResultCardsDrawerProps {
  open: boolean
  onClose: () => void
  exam: ExamResponseDto | null
}

export function ResultCardsDrawer({ open, onClose, exam }: ResultCardsDrawerProps) {
  const [selectedCard, setSelectedCard] = useState<ResultCardResponseDto | null>(null)
  const closeButtonRef = useRef<HTMLButtonElement>(null)
  const prevFocusedRef = useRef<HTMLElement | null>(null)

  // School name for the printable report-card header (cached 5m).
  const { data: school } = useSchoolProfile(exam?.schoolId ?? null, !!exam)

  useEffect(() => {
    if (!open) setSelectedCard(null)
  }, [open])

  // Modal a11y: focus the close button on open, restore focus on close.
  // Keyed only on `open` so a parent re-render (fresh onClose identity) doesn't
  // yank focus while the drawer stays open.
  useEffect(() => {
    if (open) {
      prevFocusedRef.current = document.activeElement as HTMLElement | null
      closeButtonRef.current?.focus()
    } else {
      prevFocusedRef.current?.focus()
    }
  }, [open])

  // ESC to close (separate so its onClose dependency can't disturb focus).
  useEffect(() => {
    if (!open) return
    const handleEscape = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose()
    }
    document.addEventListener('keydown', handleEscape)
    return () => document.removeEventListener('keydown', handleEscape)
  }, [open, onClose])

  return (
    <AnimatePresence>
      {open && exam && (
        <div className="fixed inset-0 z-50" role="dialog" aria-modal="true" aria-labelledby="result-cards-title">
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.2 }}
            className="fixed inset-0 bg-[rgb(var(--background-overlay)/0.30)] backdrop-blur-sm"
            onClick={(e) => {
              if (e.target === e.currentTarget) onClose()
            }}
            aria-hidden="true"
          />
          <div className="fixed inset-y-0 right-0 flex max-w-full pl-10">
            <motion.div
              initial={{ x: '100%' }}
              animate={{ x: 0 }}
              exit={{ x: '100%' }}
              transition={{ type: 'spring', damping: 30, stiffness: 300 }}
              className="w-screen max-w-2xl h-full"
            >
              <div className="flex h-full flex-col bg-surface-primary shadow-xl border-l border-border-secondary">
                <div className="flex items-center justify-between px-6 py-4 border-b border-border-secondary">
                  <div className="flex items-center gap-3 min-w-0">
                    <div className="p-2 rounded-lg bg-gradient-to-br from-[rgb(var(--state-success-bg)/0.18)] to-[rgb(var(--state-success-bg)/0.10)] flex-shrink-0">
                      <ClipboardList className="w-5 h-5 text-[rgb(var(--state-success-fg))]" />
                    </div>
                    <div className="min-w-0">
                      <h2 id="result-cards-title" className="text-lg font-semibold text-text-primary truncate">
                        Result Cards
                      </h2>
                      <p className="text-xs text-text-tertiary truncate">
                        {exam.examName} · {humanizeExamType(exam.examType)}
                      </p>
                    </div>
                  </div>
                  <button
                    type="button"
                    ref={closeButtonRef}
                    onClick={onClose}
                    className="p-1.5 rounded-lg text-text-tertiary hover:text-text-primary hover:bg-surface-secondary transition-colors flex-shrink-0"
                    aria-label="Close drawer"
                  >
                    <X className="w-5 h-5" />
                  </button>
                </div>

                {selectedCard ? (
                  <ReportCardDetail
                    card={selectedCard}
                    exam={exam}
                    schoolName={school?.name}
                    onBack={() => setSelectedCard(null)}
                    onCardUpdated={setSelectedCard}
                  />
                ) : (
                  <ResultCardList exam={exam} onSelect={setSelectedCard} />
                )}
              </div>
            </motion.div>
          </div>
        </div>
      )}
    </AnimatePresence>
  )
}
