/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MissingTenantRouteImport } from './routes/missing-tenant'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedPeopleRouteImport } from './routes/_protected/people'
import { Route as ProtectedHomeRouteImport } from './routes/_protected/home'
import { Route as ProtectedFinanceRouteImport } from './routes/_protected/finance'
import { Route as ProtectedAcademicsRouteImport } from './routes/_protected/academics'
import { Route as ProtectedSettingsIndexRouteImport } from './routes/_protected/settings/index'

const MissingTenantRoute = MissingTenantRouteImport.update({
  id: '/missing-tenant',
  path: '/missing-tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPeopleRoute = ProtectedPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedHomeRoute = ProtectedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedFinanceRoute = ProtectedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAcademicsRoute = ProtectedAcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsIndexRoute = ProtectedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/missing-tenant': typeof MissingTenantRoute
  '/academics': typeof ProtectedAcademicsRoute
  '/finance': typeof ProtectedFinanceRoute
  '/home': typeof ProtectedHomeRoute
  '/people': typeof ProtectedPeopleRoute
  '/': typeof ProtectedIndexRoute
  '/settings': typeof ProtectedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/missing-tenant': typeof MissingTenantRoute
  '/academics': typeof ProtectedAcademicsRoute
  '/finance': typeof ProtectedFinanceRoute
  '/home': typeof ProtectedHomeRoute
  '/people': typeof ProtectedPeopleRoute
  '/': typeof ProtectedIndexRoute
  '/settings': typeof ProtectedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/missing-tenant': typeof MissingTenantRoute
  '/_protected/academics': typeof ProtectedAcademicsRoute
  '/_protected/finance': typeof ProtectedFinanceRoute
  '/_protected/home': typeof ProtectedHomeRoute
  '/_protected/people': typeof ProtectedPeopleRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/settings/': typeof ProtectedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/forbidden'
    | '/login'
    | '/missing-tenant'
    | '/academics'
    | '/finance'
    | '/home'
    | '/people'
    | '/'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forbidden'
    | '/login'
    | '/missing-tenant'
    | '/academics'
    | '/finance'
    | '/home'
    | '/people'
    | '/'
    | '/settings'
  id:
    | '__root__'
    | '/_protected'
    | '/forbidden'
    | '/login'
    | '/missing-tenant'
    | '/_protected/academics'
    | '/_protected/finance'
    | '/_protected/home'
    | '/_protected/people'
    | '/_protected/'
    | '/_protected/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
  LoginRoute: typeof LoginRoute
  MissingTenantRoute: typeof MissingTenantRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/missing-tenant': {
      id: '/missing-tenant'
      path: '/missing-tenant'
      fullPath: '/missing-tenant'
      preLoaderRoute: typeof MissingTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/people': {
      id: '/_protected/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof ProtectedPeopleRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/home': {
      id: '/_protected/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof ProtectedHomeRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/finance': {
      id: '/_protected/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof ProtectedFinanceRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/academics': {
      id: '/_protected/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof ProtectedAcademicsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/': {
      id: '/_protected/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedAcademicsRoute: typeof ProtectedAcademicsRoute
  ProtectedFinanceRoute: typeof ProtectedFinanceRoute
  ProtectedHomeRoute: typeof ProtectedHomeRoute
  ProtectedPeopleRoute: typeof ProtectedPeopleRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedSettingsIndexRoute: typeof ProtectedSettingsIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAcademicsRoute: ProtectedAcademicsRoute,
  ProtectedFinanceRoute: ProtectedFinanceRoute,
  ProtectedHomeRoute: ProtectedHomeRoute,
  ProtectedPeopleRoute: ProtectedPeopleRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedSettingsIndexRoute: ProtectedSettingsIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
  LoginRoute: LoginRoute,
  MissingTenantRoute: MissingTenantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
