/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MissingTenantRouteImport } from './routes/missing-tenant'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedStudentPortalRouteImport } from './routes/_protected/student-portal'
import { Route as ProtectedPeopleRouteImport } from './routes/_protected/people'
import { Route as ProtectedParentPortalRouteImport } from './routes/_protected/parent-portal'
import { Route as ProtectedMessagesRouteImport } from './routes/_protected/messages'
import { Route as ProtectedHomeRouteImport } from './routes/_protected/home'
import { Route as ProtectedFinanceRouteImport } from './routes/_protected/finance'
import { Route as ProtectedAnalyticsRouteImport } from './routes/_protected/analytics'
import { Route as ProtectedAcademicsRouteImport } from './routes/_protected/academics'
import { Route as ProtectedSettingsIndexRouteImport } from './routes/_protected/settings/index'
import { Route as ProtectedMessagesIndexRouteImport } from './routes/_protected/messages/index'
import { Route as ProtectedStudentPortalScheduleRouteImport } from './routes/_protected/student-portal/schedule'
import { Route as ProtectedStudentPortalGradesRouteImport } from './routes/_protected/student-portal/grades'
import { Route as ProtectedStudentPortalAttendanceRouteImport } from './routes/_protected/student-portal/attendance'
import { Route as ProtectedStudentPortalAssignmentsRouteImport } from './routes/_protected/student-portal/assignments'
import { Route as ProtectedSettingsSecurityRouteImport } from './routes/_protected/settings/security'
import { Route as ProtectedSettingsSchoolsRouteImport } from './routes/_protected/settings/schools'
import { Route as ProtectedSettingsPreferencesRouteImport } from './routes/_protected/settings/preferences'
import { Route as ProtectedSettingsPeopleRouteImport } from './routes/_protected/settings/people'
import { Route as ProtectedSettingsNotificationsRouteImport } from './routes/_protected/settings/notifications'
import { Route as ProtectedSettingsIntegrationsRouteImport } from './routes/_protected/settings/integrations'
import { Route as ProtectedSettingsGeneralRouteImport } from './routes/_protected/settings/general'
import { Route as ProtectedSettingsDataRouteImport } from './routes/_protected/settings/data'
import { Route as ProtectedSettingsDangerRouteImport } from './routes/_protected/settings/danger'
import { Route as ProtectedSettingsConnectionsRouteImport } from './routes/_protected/settings/connections'
import { Route as ProtectedSettingsBillingRouteImport } from './routes/_protected/settings/billing'
import { Route as ProtectedSettingsAccountRouteImport } from './routes/_protected/settings/account'
import { Route as ProtectedPeopleStaffRouteImport } from './routes/_protected/people/staff'
import { Route as ProtectedPeopleReportingRouteImport } from './routes/_protected/people/reporting'
import { Route as ProtectedPeopleParentsRouteImport } from './routes/_protected/people/parents'
import { Route as ProtectedPeopleNewRouteImport } from './routes/_protected/people/new'
import { Route as ProtectedPeopleDepartmentRouteImport } from './routes/_protected/people/department'
import { Route as ProtectedPeopleAttendanceRouteImport } from './routes/_protected/people/attendance'
import { Route as ProtectedPeopleAssignmentsRouteImport } from './routes/_protected/people/assignments'
import { Route as ProtectedParentPortalGradesRouteImport } from './routes/_protected/parent-portal/grades'
import { Route as ProtectedParentPortalFeesRouteImport } from './routes/_protected/parent-portal/fees'
import { Route as ProtectedParentPortalAttendanceRouteImport } from './routes/_protected/parent-portal/attendance'
import { Route as ProtectedMessagesMeetingsRouteImport } from './routes/_protected/messages/meetings'
import { Route as ProtectedMessagesIntegrationsRouteImport } from './routes/_protected/messages/integrations'
import { Route as ProtectedMessagesInboxRouteImport } from './routes/_protected/messages/inbox'
import { Route as ProtectedMessagesAnnouncementsRouteImport } from './routes/_protected/messages/announcements'
import { Route as ProtectedFinanceTuitionandfeesRouteImport } from './routes/_protected/finance/tuitionandfees'
import { Route as ProtectedFinanceReportsRouteImport } from './routes/_protected/finance/reports'
import { Route as ProtectedFinancePayrollRouteImport } from './routes/_protected/finance/payroll'
import { Route as ProtectedFinanceFinancialsRouteImport } from './routes/_protected/finance/financials'
import { Route as ProtectedFinanceExpensesRouteImport } from './routes/_protected/finance/expenses'
import { Route as ProtectedAnalyticsFinancialRouteImport } from './routes/_protected/analytics/financial'
import { Route as ProtectedAnalyticsAcademicRouteImport } from './routes/_protected/analytics/academic'
import { Route as ProtectedAcademicsTeachersRouteImport } from './routes/_protected/academics/teachers'
import { Route as ProtectedAcademicsStudentsRouteImport } from './routes/_protected/academics/students'
import { Route as ProtectedAcademicsSchoolcalendarRouteImport } from './routes/_protected/academics/schoolcalendar'
import { Route as ProtectedAcademicsReportingRouteImport } from './routes/_protected/academics/reporting'
import { Route as ProtectedAcademicsGradelevelsRouteImport } from './routes/_protected/academics/gradelevels'
import { Route as ProtectedAcademicsGradebooksRouteImport } from './routes/_protected/academics/gradebooks'
import { Route as ProtectedAcademicsEnrollmentRouteImport } from './routes/_protected/academics/enrollment'
import { Route as ProtectedAcademicsCurriculumRouteImport } from './routes/_protected/academics/curriculum'
import { Route as ProtectedAcademicsClassroomsRouteImport } from './routes/_protected/academics/classrooms'
import { Route as ProtectedAcademicsAttendanceRouteImport } from './routes/_protected/academics/attendance'
import { Route as ProtectedPeopleStaffStaffIdRouteImport } from './routes/_protected/people/staff/$staffId'
import { Route as ProtectedPeopleParentsParentIdRouteImport } from './routes/_protected/people/parents/$parentId'
import { Route as ProtectedAcademicsTeachersTeacherIdRouteImport } from './routes/_protected/academics/teachers/$teacherId'
import { Route as ProtectedAcademicsStudentsStudentIdRouteImport } from './routes/_protected/academics/students/$studentId'
import { Route as ProtectedAcademicsGradebooksClassIdRouteImport } from './routes/_protected/academics/gradebooks/$classId'
import { Route as ProtectedAcademicsClassroomsClassroomIdRouteImport } from './routes/_protected/academics/classrooms/$classroomId'

const MissingTenantRoute = MissingTenantRouteImport.update({
  id: '/missing-tenant',
  path: '/missing-tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedStudentPortalRoute = ProtectedStudentPortalRouteImport.update({
  id: '/student-portal',
  path: '/student-portal',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPeopleRoute = ProtectedPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedParentPortalRoute = ProtectedParentPortalRouteImport.update({
  id: '/parent-portal',
  path: '/parent-portal',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMessagesRoute = ProtectedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedHomeRoute = ProtectedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedFinanceRoute = ProtectedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAnalyticsRoute = ProtectedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAcademicsRoute = ProtectedAcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsIndexRoute = ProtectedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMessagesIndexRoute = ProtectedMessagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedMessagesRoute,
} as any)
const ProtectedStudentPortalScheduleRoute =
  ProtectedStudentPortalScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => ProtectedStudentPortalRoute,
  } as any)
const ProtectedStudentPortalGradesRoute =
  ProtectedStudentPortalGradesRouteImport.update({
    id: '/grades',
    path: '/grades',
    getParentRoute: () => ProtectedStudentPortalRoute,
  } as any)
const ProtectedStudentPortalAttendanceRoute =
  ProtectedStudentPortalAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => ProtectedStudentPortalRoute,
  } as any)
const ProtectedStudentPortalAssignmentsRoute =
  ProtectedStudentPortalAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => ProtectedStudentPortalRoute,
  } as any)
const ProtectedSettingsSecurityRoute =
  ProtectedSettingsSecurityRouteImport.update({
    id: '/settings/security',
    path: '/settings/security',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsSchoolsRoute =
  ProtectedSettingsSchoolsRouteImport.update({
    id: '/settings/schools',
    path: '/settings/schools',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsPreferencesRoute =
  ProtectedSettingsPreferencesRouteImport.update({
    id: '/settings/preferences',
    path: '/settings/preferences',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsPeopleRoute = ProtectedSettingsPeopleRouteImport.update({
  id: '/settings/people',
  path: '/settings/people',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsNotificationsRoute =
  ProtectedSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsIntegrationsRoute =
  ProtectedSettingsIntegrationsRouteImport.update({
    id: '/settings/integrations',
    path: '/settings/integrations',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsGeneralRoute =
  ProtectedSettingsGeneralRouteImport.update({
    id: '/settings/general',
    path: '/settings/general',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsDataRoute = ProtectedSettingsDataRouteImport.update({
  id: '/settings/data',
  path: '/settings/data',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsDangerRoute = ProtectedSettingsDangerRouteImport.update({
  id: '/settings/danger',
  path: '/settings/danger',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsConnectionsRoute =
  ProtectedSettingsConnectionsRouteImport.update({
    id: '/settings/connections',
    path: '/settings/connections',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsBillingRoute =
  ProtectedSettingsBillingRouteImport.update({
    id: '/settings/billing',
    path: '/settings/billing',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsAccountRoute =
  ProtectedSettingsAccountRouteImport.update({
    id: '/settings/account',
    path: '/settings/account',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedPeopleStaffRoute = ProtectedPeopleStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => ProtectedPeopleRoute,
} as any)
const ProtectedPeopleReportingRoute =
  ProtectedPeopleReportingRouteImport.update({
    id: '/reporting',
    path: '/reporting',
    getParentRoute: () => ProtectedPeopleRoute,
  } as any)
const ProtectedPeopleParentsRoute = ProtectedPeopleParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => ProtectedPeopleRoute,
} as any)
const ProtectedPeopleNewRoute = ProtectedPeopleNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProtectedPeopleRoute,
} as any)
const ProtectedPeopleDepartmentRoute =
  ProtectedPeopleDepartmentRouteImport.update({
    id: '/department',
    path: '/department',
    getParentRoute: () => ProtectedPeopleRoute,
  } as any)
const ProtectedPeopleAttendanceRoute =
  ProtectedPeopleAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => ProtectedPeopleRoute,
  } as any)
const ProtectedPeopleAssignmentsRoute =
  ProtectedPeopleAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => ProtectedPeopleRoute,
  } as any)
const ProtectedParentPortalGradesRoute =
  ProtectedParentPortalGradesRouteImport.update({
    id: '/grades',
    path: '/grades',
    getParentRoute: () => ProtectedParentPortalRoute,
  } as any)
const ProtectedParentPortalFeesRoute =
  ProtectedParentPortalFeesRouteImport.update({
    id: '/fees',
    path: '/fees',
    getParentRoute: () => ProtectedParentPortalRoute,
  } as any)
const ProtectedParentPortalAttendanceRoute =
  ProtectedParentPortalAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => ProtectedParentPortalRoute,
  } as any)
const ProtectedMessagesMeetingsRoute =
  ProtectedMessagesMeetingsRouteImport.update({
    id: '/meetings',
    path: '/meetings',
    getParentRoute: () => ProtectedMessagesRoute,
  } as any)
const ProtectedMessagesIntegrationsRoute =
  ProtectedMessagesIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => ProtectedMessagesRoute,
  } as any)
const ProtectedMessagesInboxRoute = ProtectedMessagesInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => ProtectedMessagesRoute,
} as any)
const ProtectedMessagesAnnouncementsRoute =
  ProtectedMessagesAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => ProtectedMessagesRoute,
  } as any)
const ProtectedFinanceTuitionandfeesRoute =
  ProtectedFinanceTuitionandfeesRouteImport.update({
    id: '/tuitionandfees',
    path: '/tuitionandfees',
    getParentRoute: () => ProtectedFinanceRoute,
  } as any)
const ProtectedFinanceReportsRoute = ProtectedFinanceReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ProtectedFinanceRoute,
} as any)
const ProtectedFinancePayrollRoute = ProtectedFinancePayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => ProtectedFinanceRoute,
} as any)
const ProtectedFinanceFinancialsRoute =
  ProtectedFinanceFinancialsRouteImport.update({
    id: '/financials',
    path: '/financials',
    getParentRoute: () => ProtectedFinanceRoute,
  } as any)
const ProtectedFinanceExpensesRoute =
  ProtectedFinanceExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => ProtectedFinanceRoute,
  } as any)
const ProtectedAnalyticsFinancialRoute =
  ProtectedAnalyticsFinancialRouteImport.update({
    id: '/financial',
    path: '/financial',
    getParentRoute: () => ProtectedAnalyticsRoute,
  } as any)
const ProtectedAnalyticsAcademicRoute =
  ProtectedAnalyticsAcademicRouteImport.update({
    id: '/academic',
    path: '/academic',
    getParentRoute: () => ProtectedAnalyticsRoute,
  } as any)
const ProtectedAcademicsTeachersRoute =
  ProtectedAcademicsTeachersRouteImport.update({
    id: '/teachers',
    path: '/teachers',
    getParentRoute: () => ProtectedAcademicsRoute,
  } as any)
const ProtectedAcademicsStudentsRoute =
  ProtectedAcademicsStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => ProtectedAcademicsRoute,
  } as any)
const ProtectedAcademicsSchoolcalendarRoute =
  ProtectedAcademicsSchoolcalendarRouteImport.update({
    id: '/schoolcalendar',
    path: '/schoolcalendar',
    getParentRoute: () => ProtectedAcademicsRoute,
  } as any)
const ProtectedAcademicsReportingRoute =
  ProtectedAcademicsReportingRouteImport.update({
    id: '/reporting',
    path: '/reporting',
    getParentRoute: () => ProtectedAcademicsRoute,
  } as any)
const ProtectedAcademicsGradelevelsRoute =
  ProtectedAcademicsGradelevelsRouteImport.update({
    id: '/gradelevels',
    path: '/gradelevels',
    getParentRoute: () => ProtectedAcademicsRoute,
  } as any)
const ProtectedAcademicsGradebooksRoute =
  ProtectedAcademicsGradebooksRouteImport.update({
    id: '/gradebooks',
    path: '/gradebooks',
    getParentRoute: () => ProtectedAcademicsRoute,
  } as any)
const ProtectedAcademicsEnrollmentRoute =
  ProtectedAcademicsEnrollmentRouteImport.update({
    id: '/enrollment',
    path: '/enrollment',
    getParentRoute: () => ProtectedAcademicsRoute,
  } as any)
const ProtectedAcademicsCurriculumRoute =
  ProtectedAcademicsCurriculumRouteImport.update({
    id: '/curriculum',
    path: '/curriculum',
    getParentRoute: () => ProtectedAcademicsRoute,
  } as any)
const ProtectedAcademicsClassroomsRoute =
  ProtectedAcademicsClassroomsRouteImport.update({
    id: '/classrooms',
    path: '/classrooms',
    getParentRoute: () => ProtectedAcademicsRoute,
  } as any)
const ProtectedAcademicsAttendanceRoute =
  ProtectedAcademicsAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => ProtectedAcademicsRoute,
  } as any)
const ProtectedPeopleStaffStaffIdRoute =
  ProtectedPeopleStaffStaffIdRouteImport.update({
    id: '/$staffId',
    path: '/$staffId',
    getParentRoute: () => ProtectedPeopleStaffRoute,
  } as any)
const ProtectedPeopleParentsParentIdRoute =
  ProtectedPeopleParentsParentIdRouteImport.update({
    id: '/$parentId',
    path: '/$parentId',
    getParentRoute: () => ProtectedPeopleParentsRoute,
  } as any)
const ProtectedAcademicsTeachersTeacherIdRoute =
  ProtectedAcademicsTeachersTeacherIdRouteImport.update({
    id: '/$teacherId',
    path: '/$teacherId',
    getParentRoute: () => ProtectedAcademicsTeachersRoute,
  } as any)
const ProtectedAcademicsStudentsStudentIdRoute =
  ProtectedAcademicsStudentsStudentIdRouteImport.update({
    id: '/$studentId',
    path: '/$studentId',
    getParentRoute: () => ProtectedAcademicsStudentsRoute,
  } as any)
const ProtectedAcademicsGradebooksClassIdRoute =
  ProtectedAcademicsGradebooksClassIdRouteImport.update({
    id: '/$classId',
    path: '/$classId',
    getParentRoute: () => ProtectedAcademicsGradebooksRoute,
  } as any)
const ProtectedAcademicsClassroomsClassroomIdRoute =
  ProtectedAcademicsClassroomsClassroomIdRouteImport.update({
    id: '/$classroomId',
    path: '/$classroomId',
    getParentRoute: () => ProtectedAcademicsClassroomsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/missing-tenant': typeof MissingTenantRoute
  '/academics': typeof ProtectedAcademicsRouteWithChildren
  '/analytics': typeof ProtectedAnalyticsRouteWithChildren
  '/finance': typeof ProtectedFinanceRouteWithChildren
  '/home': typeof ProtectedHomeRoute
  '/messages': typeof ProtectedMessagesRouteWithChildren
  '/parent-portal': typeof ProtectedParentPortalRouteWithChildren
  '/people': typeof ProtectedPeopleRouteWithChildren
  '/student-portal': typeof ProtectedStudentPortalRouteWithChildren
  '/': typeof ProtectedIndexRoute
  '/academics/attendance': typeof ProtectedAcademicsAttendanceRoute
  '/academics/classrooms': typeof ProtectedAcademicsClassroomsRouteWithChildren
  '/academics/curriculum': typeof ProtectedAcademicsCurriculumRoute
  '/academics/enrollment': typeof ProtectedAcademicsEnrollmentRoute
  '/academics/gradebooks': typeof ProtectedAcademicsGradebooksRouteWithChildren
  '/academics/gradelevels': typeof ProtectedAcademicsGradelevelsRoute
  '/academics/reporting': typeof ProtectedAcademicsReportingRoute
  '/academics/schoolcalendar': typeof ProtectedAcademicsSchoolcalendarRoute
  '/academics/students': typeof ProtectedAcademicsStudentsRouteWithChildren
  '/academics/teachers': typeof ProtectedAcademicsTeachersRouteWithChildren
  '/analytics/academic': typeof ProtectedAnalyticsAcademicRoute
  '/analytics/financial': typeof ProtectedAnalyticsFinancialRoute
  '/finance/expenses': typeof ProtectedFinanceExpensesRoute
  '/finance/financials': typeof ProtectedFinanceFinancialsRoute
  '/finance/payroll': typeof ProtectedFinancePayrollRoute
  '/finance/reports': typeof ProtectedFinanceReportsRoute
  '/finance/tuitionandfees': typeof ProtectedFinanceTuitionandfeesRoute
  '/messages/announcements': typeof ProtectedMessagesAnnouncementsRoute
  '/messages/inbox': typeof ProtectedMessagesInboxRoute
  '/messages/integrations': typeof ProtectedMessagesIntegrationsRoute
  '/messages/meetings': typeof ProtectedMessagesMeetingsRoute
  '/parent-portal/attendance': typeof ProtectedParentPortalAttendanceRoute
  '/parent-portal/fees': typeof ProtectedParentPortalFeesRoute
  '/parent-portal/grades': typeof ProtectedParentPortalGradesRoute
  '/people/assignments': typeof ProtectedPeopleAssignmentsRoute
  '/people/attendance': typeof ProtectedPeopleAttendanceRoute
  '/people/department': typeof ProtectedPeopleDepartmentRoute
  '/people/new': typeof ProtectedPeopleNewRoute
  '/people/parents': typeof ProtectedPeopleParentsRouteWithChildren
  '/people/reporting': typeof ProtectedPeopleReportingRoute
  '/people/staff': typeof ProtectedPeopleStaffRouteWithChildren
  '/settings/account': typeof ProtectedSettingsAccountRoute
  '/settings/billing': typeof ProtectedSettingsBillingRoute
  '/settings/connections': typeof ProtectedSettingsConnectionsRoute
  '/settings/danger': typeof ProtectedSettingsDangerRoute
  '/settings/data': typeof ProtectedSettingsDataRoute
  '/settings/general': typeof ProtectedSettingsGeneralRoute
  '/settings/integrations': typeof ProtectedSettingsIntegrationsRoute
  '/settings/notifications': typeof ProtectedSettingsNotificationsRoute
  '/settings/people': typeof ProtectedSettingsPeopleRoute
  '/settings/preferences': typeof ProtectedSettingsPreferencesRoute
  '/settings/schools': typeof ProtectedSettingsSchoolsRoute
  '/settings/security': typeof ProtectedSettingsSecurityRoute
  '/student-portal/assignments': typeof ProtectedStudentPortalAssignmentsRoute
  '/student-portal/attendance': typeof ProtectedStudentPortalAttendanceRoute
  '/student-portal/grades': typeof ProtectedStudentPortalGradesRoute
  '/student-portal/schedule': typeof ProtectedStudentPortalScheduleRoute
  '/messages/': typeof ProtectedMessagesIndexRoute
  '/settings': typeof ProtectedSettingsIndexRoute
  '/academics/classrooms/$classroomId': typeof ProtectedAcademicsClassroomsClassroomIdRoute
  '/academics/gradebooks/$classId': typeof ProtectedAcademicsGradebooksClassIdRoute
  '/academics/students/$studentId': typeof ProtectedAcademicsStudentsStudentIdRoute
  '/academics/teachers/$teacherId': typeof ProtectedAcademicsTeachersTeacherIdRoute
  '/people/parents/$parentId': typeof ProtectedPeopleParentsParentIdRoute
  '/people/staff/$staffId': typeof ProtectedPeopleStaffStaffIdRoute
}
export interface FileRoutesByTo {
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/missing-tenant': typeof MissingTenantRoute
  '/academics': typeof ProtectedAcademicsRouteWithChildren
  '/analytics': typeof ProtectedAnalyticsRouteWithChildren
  '/finance': typeof ProtectedFinanceRouteWithChildren
  '/home': typeof ProtectedHomeRoute
  '/parent-portal': typeof ProtectedParentPortalRouteWithChildren
  '/people': typeof ProtectedPeopleRouteWithChildren
  '/student-portal': typeof ProtectedStudentPortalRouteWithChildren
  '/': typeof ProtectedIndexRoute
  '/academics/attendance': typeof ProtectedAcademicsAttendanceRoute
  '/academics/classrooms': typeof ProtectedAcademicsClassroomsRouteWithChildren
  '/academics/curriculum': typeof ProtectedAcademicsCurriculumRoute
  '/academics/enrollment': typeof ProtectedAcademicsEnrollmentRoute
  '/academics/gradebooks': typeof ProtectedAcademicsGradebooksRouteWithChildren
  '/academics/gradelevels': typeof ProtectedAcademicsGradelevelsRoute
  '/academics/reporting': typeof ProtectedAcademicsReportingRoute
  '/academics/schoolcalendar': typeof ProtectedAcademicsSchoolcalendarRoute
  '/academics/students': typeof ProtectedAcademicsStudentsRouteWithChildren
  '/academics/teachers': typeof ProtectedAcademicsTeachersRouteWithChildren
  '/analytics/academic': typeof ProtectedAnalyticsAcademicRoute
  '/analytics/financial': typeof ProtectedAnalyticsFinancialRoute
  '/finance/expenses': typeof ProtectedFinanceExpensesRoute
  '/finance/financials': typeof ProtectedFinanceFinancialsRoute
  '/finance/payroll': typeof ProtectedFinancePayrollRoute
  '/finance/reports': typeof ProtectedFinanceReportsRoute
  '/finance/tuitionandfees': typeof ProtectedFinanceTuitionandfeesRoute
  '/messages/announcements': typeof ProtectedMessagesAnnouncementsRoute
  '/messages/inbox': typeof ProtectedMessagesInboxRoute
  '/messages/integrations': typeof ProtectedMessagesIntegrationsRoute
  '/messages/meetings': typeof ProtectedMessagesMeetingsRoute
  '/parent-portal/attendance': typeof ProtectedParentPortalAttendanceRoute
  '/parent-portal/fees': typeof ProtectedParentPortalFeesRoute
  '/parent-portal/grades': typeof ProtectedParentPortalGradesRoute
  '/people/assignments': typeof ProtectedPeopleAssignmentsRoute
  '/people/attendance': typeof ProtectedPeopleAttendanceRoute
  '/people/department': typeof ProtectedPeopleDepartmentRoute
  '/people/new': typeof ProtectedPeopleNewRoute
  '/people/parents': typeof ProtectedPeopleParentsRouteWithChildren
  '/people/reporting': typeof ProtectedPeopleReportingRoute
  '/people/staff': typeof ProtectedPeopleStaffRouteWithChildren
  '/settings/account': typeof ProtectedSettingsAccountRoute
  '/settings/billing': typeof ProtectedSettingsBillingRoute
  '/settings/connections': typeof ProtectedSettingsConnectionsRoute
  '/settings/danger': typeof ProtectedSettingsDangerRoute
  '/settings/data': typeof ProtectedSettingsDataRoute
  '/settings/general': typeof ProtectedSettingsGeneralRoute
  '/settings/integrations': typeof ProtectedSettingsIntegrationsRoute
  '/settings/notifications': typeof ProtectedSettingsNotificationsRoute
  '/settings/people': typeof ProtectedSettingsPeopleRoute
  '/settings/preferences': typeof ProtectedSettingsPreferencesRoute
  '/settings/schools': typeof ProtectedSettingsSchoolsRoute
  '/settings/security': typeof ProtectedSettingsSecurityRoute
  '/student-portal/assignments': typeof ProtectedStudentPortalAssignmentsRoute
  '/student-portal/attendance': typeof ProtectedStudentPortalAttendanceRoute
  '/student-portal/grades': typeof ProtectedStudentPortalGradesRoute
  '/student-portal/schedule': typeof ProtectedStudentPortalScheduleRoute
  '/messages': typeof ProtectedMessagesIndexRoute
  '/settings': typeof ProtectedSettingsIndexRoute
  '/academics/classrooms/$classroomId': typeof ProtectedAcademicsClassroomsClassroomIdRoute
  '/academics/gradebooks/$classId': typeof ProtectedAcademicsGradebooksClassIdRoute
  '/academics/students/$studentId': typeof ProtectedAcademicsStudentsStudentIdRoute
  '/academics/teachers/$teacherId': typeof ProtectedAcademicsTeachersTeacherIdRoute
  '/people/parents/$parentId': typeof ProtectedPeopleParentsParentIdRoute
  '/people/staff/$staffId': typeof ProtectedPeopleStaffStaffIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/missing-tenant': typeof MissingTenantRoute
  '/_protected/academics': typeof ProtectedAcademicsRouteWithChildren
  '/_protected/analytics': typeof ProtectedAnalyticsRouteWithChildren
  '/_protected/finance': typeof ProtectedFinanceRouteWithChildren
  '/_protected/home': typeof ProtectedHomeRoute
  '/_protected/messages': typeof ProtectedMessagesRouteWithChildren
  '/_protected/parent-portal': typeof ProtectedParentPortalRouteWithChildren
  '/_protected/people': typeof ProtectedPeopleRouteWithChildren
  '/_protected/student-portal': typeof ProtectedStudentPortalRouteWithChildren
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/academics/attendance': typeof ProtectedAcademicsAttendanceRoute
  '/_protected/academics/classrooms': typeof ProtectedAcademicsClassroomsRouteWithChildren
  '/_protected/academics/curriculum': typeof ProtectedAcademicsCurriculumRoute
  '/_protected/academics/enrollment': typeof ProtectedAcademicsEnrollmentRoute
  '/_protected/academics/gradebooks': typeof ProtectedAcademicsGradebooksRouteWithChildren
  '/_protected/academics/gradelevels': typeof ProtectedAcademicsGradelevelsRoute
  '/_protected/academics/reporting': typeof ProtectedAcademicsReportingRoute
  '/_protected/academics/schoolcalendar': typeof ProtectedAcademicsSchoolcalendarRoute
  '/_protected/academics/students': typeof ProtectedAcademicsStudentsRouteWithChildren
  '/_protected/academics/teachers': typeof ProtectedAcademicsTeachersRouteWithChildren
  '/_protected/analytics/academic': typeof ProtectedAnalyticsAcademicRoute
  '/_protected/analytics/financial': typeof ProtectedAnalyticsFinancialRoute
  '/_protected/finance/expenses': typeof ProtectedFinanceExpensesRoute
  '/_protected/finance/financials': typeof ProtectedFinanceFinancialsRoute
  '/_protected/finance/payroll': typeof ProtectedFinancePayrollRoute
  '/_protected/finance/reports': typeof ProtectedFinanceReportsRoute
  '/_protected/finance/tuitionandfees': typeof ProtectedFinanceTuitionandfeesRoute
  '/_protected/messages/announcements': typeof ProtectedMessagesAnnouncementsRoute
  '/_protected/messages/inbox': typeof ProtectedMessagesInboxRoute
  '/_protected/messages/integrations': typeof ProtectedMessagesIntegrationsRoute
  '/_protected/messages/meetings': typeof ProtectedMessagesMeetingsRoute
  '/_protected/parent-portal/attendance': typeof ProtectedParentPortalAttendanceRoute
  '/_protected/parent-portal/fees': typeof ProtectedParentPortalFeesRoute
  '/_protected/parent-portal/grades': typeof ProtectedParentPortalGradesRoute
  '/_protected/people/assignments': typeof ProtectedPeopleAssignmentsRoute
  '/_protected/people/attendance': typeof ProtectedPeopleAttendanceRoute
  '/_protected/people/department': typeof ProtectedPeopleDepartmentRoute
  '/_protected/people/new': typeof ProtectedPeopleNewRoute
  '/_protected/people/parents': typeof ProtectedPeopleParentsRouteWithChildren
  '/_protected/people/reporting': typeof ProtectedPeopleReportingRoute
  '/_protected/people/staff': typeof ProtectedPeopleStaffRouteWithChildren
  '/_protected/settings/account': typeof ProtectedSettingsAccountRoute
  '/_protected/settings/billing': typeof ProtectedSettingsBillingRoute
  '/_protected/settings/connections': typeof ProtectedSettingsConnectionsRoute
  '/_protected/settings/danger': typeof ProtectedSettingsDangerRoute
  '/_protected/settings/data': typeof ProtectedSettingsDataRoute
  '/_protected/settings/general': typeof ProtectedSettingsGeneralRoute
  '/_protected/settings/integrations': typeof ProtectedSettingsIntegrationsRoute
  '/_protected/settings/notifications': typeof ProtectedSettingsNotificationsRoute
  '/_protected/settings/people': typeof ProtectedSettingsPeopleRoute
  '/_protected/settings/preferences': typeof ProtectedSettingsPreferencesRoute
  '/_protected/settings/schools': typeof ProtectedSettingsSchoolsRoute
  '/_protected/settings/security': typeof ProtectedSettingsSecurityRoute
  '/_protected/student-portal/assignments': typeof ProtectedStudentPortalAssignmentsRoute
  '/_protected/student-portal/attendance': typeof ProtectedStudentPortalAttendanceRoute
  '/_protected/student-portal/grades': typeof ProtectedStudentPortalGradesRoute
  '/_protected/student-portal/schedule': typeof ProtectedStudentPortalScheduleRoute
  '/_protected/messages/': typeof ProtectedMessagesIndexRoute
  '/_protected/settings/': typeof ProtectedSettingsIndexRoute
  '/_protected/academics/classrooms/$classroomId': typeof ProtectedAcademicsClassroomsClassroomIdRoute
  '/_protected/academics/gradebooks/$classId': typeof ProtectedAcademicsGradebooksClassIdRoute
  '/_protected/academics/students/$studentId': typeof ProtectedAcademicsStudentsStudentIdRoute
  '/_protected/academics/teachers/$teacherId': typeof ProtectedAcademicsTeachersTeacherIdRoute
  '/_protected/people/parents/$parentId': typeof ProtectedPeopleParentsParentIdRoute
  '/_protected/people/staff/$staffId': typeof ProtectedPeopleStaffStaffIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/forbidden'
    | '/login'
    | '/missing-tenant'
    | '/academics'
    | '/analytics'
    | '/finance'
    | '/home'
    | '/messages'
    | '/parent-portal'
    | '/people'
    | '/student-portal'
    | '/'
    | '/academics/attendance'
    | '/academics/classrooms'
    | '/academics/curriculum'
    | '/academics/enrollment'
    | '/academics/gradebooks'
    | '/academics/gradelevels'
    | '/academics/reporting'
    | '/academics/schoolcalendar'
    | '/academics/students'
    | '/academics/teachers'
    | '/analytics/academic'
    | '/analytics/financial'
    | '/finance/expenses'
    | '/finance/financials'
    | '/finance/payroll'
    | '/finance/reports'
    | '/finance/tuitionandfees'
    | '/messages/announcements'
    | '/messages/inbox'
    | '/messages/integrations'
    | '/messages/meetings'
    | '/parent-portal/attendance'
    | '/parent-portal/fees'
    | '/parent-portal/grades'
    | '/people/assignments'
    | '/people/attendance'
    | '/people/department'
    | '/people/new'
    | '/people/parents'
    | '/people/reporting'
    | '/people/staff'
    | '/settings/account'
    | '/settings/billing'
    | '/settings/connections'
    | '/settings/danger'
    | '/settings/data'
    | '/settings/general'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/people'
    | '/settings/preferences'
    | '/settings/schools'
    | '/settings/security'
    | '/student-portal/assignments'
    | '/student-portal/attendance'
    | '/student-portal/grades'
    | '/student-portal/schedule'
    | '/messages/'
    | '/settings'
    | '/academics/classrooms/$classroomId'
    | '/academics/gradebooks/$classId'
    | '/academics/students/$studentId'
    | '/academics/teachers/$teacherId'
    | '/people/parents/$parentId'
    | '/people/staff/$staffId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forbidden'
    | '/login'
    | '/missing-tenant'
    | '/academics'
    | '/analytics'
    | '/finance'
    | '/home'
    | '/parent-portal'
    | '/people'
    | '/student-portal'
    | '/'
    | '/academics/attendance'
    | '/academics/classrooms'
    | '/academics/curriculum'
    | '/academics/enrollment'
    | '/academics/gradebooks'
    | '/academics/gradelevels'
    | '/academics/reporting'
    | '/academics/schoolcalendar'
    | '/academics/students'
    | '/academics/teachers'
    | '/analytics/academic'
    | '/analytics/financial'
    | '/finance/expenses'
    | '/finance/financials'
    | '/finance/payroll'
    | '/finance/reports'
    | '/finance/tuitionandfees'
    | '/messages/announcements'
    | '/messages/inbox'
    | '/messages/integrations'
    | '/messages/meetings'
    | '/parent-portal/attendance'
    | '/parent-portal/fees'
    | '/parent-portal/grades'
    | '/people/assignments'
    | '/people/attendance'
    | '/people/department'
    | '/people/new'
    | '/people/parents'
    | '/people/reporting'
    | '/people/staff'
    | '/settings/account'
    | '/settings/billing'
    | '/settings/connections'
    | '/settings/danger'
    | '/settings/data'
    | '/settings/general'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/people'
    | '/settings/preferences'
    | '/settings/schools'
    | '/settings/security'
    | '/student-portal/assignments'
    | '/student-portal/attendance'
    | '/student-portal/grades'
    | '/student-portal/schedule'
    | '/messages'
    | '/settings'
    | '/academics/classrooms/$classroomId'
    | '/academics/gradebooks/$classId'
    | '/academics/students/$studentId'
    | '/academics/teachers/$teacherId'
    | '/people/parents/$parentId'
    | '/people/staff/$staffId'
  id:
    | '__root__'
    | '/_protected'
    | '/forbidden'
    | '/login'
    | '/missing-tenant'
    | '/_protected/academics'
    | '/_protected/analytics'
    | '/_protected/finance'
    | '/_protected/home'
    | '/_protected/messages'
    | '/_protected/parent-portal'
    | '/_protected/people'
    | '/_protected/student-portal'
    | '/_protected/'
    | '/_protected/academics/attendance'
    | '/_protected/academics/classrooms'
    | '/_protected/academics/curriculum'
    | '/_protected/academics/enrollment'
    | '/_protected/academics/gradebooks'
    | '/_protected/academics/gradelevels'
    | '/_protected/academics/reporting'
    | '/_protected/academics/schoolcalendar'
    | '/_protected/academics/students'
    | '/_protected/academics/teachers'
    | '/_protected/analytics/academic'
    | '/_protected/analytics/financial'
    | '/_protected/finance/expenses'
    | '/_protected/finance/financials'
    | '/_protected/finance/payroll'
    | '/_protected/finance/reports'
    | '/_protected/finance/tuitionandfees'
    | '/_protected/messages/announcements'
    | '/_protected/messages/inbox'
    | '/_protected/messages/integrations'
    | '/_protected/messages/meetings'
    | '/_protected/parent-portal/attendance'
    | '/_protected/parent-portal/fees'
    | '/_protected/parent-portal/grades'
    | '/_protected/people/assignments'
    | '/_protected/people/attendance'
    | '/_protected/people/department'
    | '/_protected/people/new'
    | '/_protected/people/parents'
    | '/_protected/people/reporting'
    | '/_protected/people/staff'
    | '/_protected/settings/account'
    | '/_protected/settings/billing'
    | '/_protected/settings/connections'
    | '/_protected/settings/danger'
    | '/_protected/settings/data'
    | '/_protected/settings/general'
    | '/_protected/settings/integrations'
    | '/_protected/settings/notifications'
    | '/_protected/settings/people'
    | '/_protected/settings/preferences'
    | '/_protected/settings/schools'
    | '/_protected/settings/security'
    | '/_protected/student-portal/assignments'
    | '/_protected/student-portal/attendance'
    | '/_protected/student-portal/grades'
    | '/_protected/student-portal/schedule'
    | '/_protected/messages/'
    | '/_protected/settings/'
    | '/_protected/academics/classrooms/$classroomId'
    | '/_protected/academics/gradebooks/$classId'
    | '/_protected/academics/students/$studentId'
    | '/_protected/academics/teachers/$teacherId'
    | '/_protected/people/parents/$parentId'
    | '/_protected/people/staff/$staffId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
  LoginRoute: typeof LoginRoute
  MissingTenantRoute: typeof MissingTenantRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/missing-tenant': {
      id: '/missing-tenant'
      path: '/missing-tenant'
      fullPath: '/missing-tenant'
      preLoaderRoute: typeof MissingTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/student-portal': {
      id: '/_protected/student-portal'
      path: '/student-portal'
      fullPath: '/student-portal'
      preLoaderRoute: typeof ProtectedStudentPortalRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/people': {
      id: '/_protected/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof ProtectedPeopleRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/parent-portal': {
      id: '/_protected/parent-portal'
      path: '/parent-portal'
      fullPath: '/parent-portal'
      preLoaderRoute: typeof ProtectedParentPortalRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/messages': {
      id: '/_protected/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof ProtectedMessagesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/home': {
      id: '/_protected/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof ProtectedHomeRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/finance': {
      id: '/_protected/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof ProtectedFinanceRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/analytics': {
      id: '/_protected/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof ProtectedAnalyticsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/academics': {
      id: '/_protected/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof ProtectedAcademicsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/': {
      id: '/_protected/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/messages/': {
      id: '/_protected/messages/'
      path: '/'
      fullPath: '/messages/'
      preLoaderRoute: typeof ProtectedMessagesIndexRouteImport
      parentRoute: typeof ProtectedMessagesRoute
    }
    '/_protected/student-portal/schedule': {
      id: '/_protected/student-portal/schedule'
      path: '/schedule'
      fullPath: '/student-portal/schedule'
      preLoaderRoute: typeof ProtectedStudentPortalScheduleRouteImport
      parentRoute: typeof ProtectedStudentPortalRoute
    }
    '/_protected/student-portal/grades': {
      id: '/_protected/student-portal/grades'
      path: '/grades'
      fullPath: '/student-portal/grades'
      preLoaderRoute: typeof ProtectedStudentPortalGradesRouteImport
      parentRoute: typeof ProtectedStudentPortalRoute
    }
    '/_protected/student-portal/attendance': {
      id: '/_protected/student-portal/attendance'
      path: '/attendance'
      fullPath: '/student-portal/attendance'
      preLoaderRoute: typeof ProtectedStudentPortalAttendanceRouteImport
      parentRoute: typeof ProtectedStudentPortalRoute
    }
    '/_protected/student-portal/assignments': {
      id: '/_protected/student-portal/assignments'
      path: '/assignments'
      fullPath: '/student-portal/assignments'
      preLoaderRoute: typeof ProtectedStudentPortalAssignmentsRouteImport
      parentRoute: typeof ProtectedStudentPortalRoute
    }
    '/_protected/settings/security': {
      id: '/_protected/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof ProtectedSettingsSecurityRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/schools': {
      id: '/_protected/settings/schools'
      path: '/settings/schools'
      fullPath: '/settings/schools'
      preLoaderRoute: typeof ProtectedSettingsSchoolsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/preferences': {
      id: '/_protected/settings/preferences'
      path: '/settings/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof ProtectedSettingsPreferencesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/people': {
      id: '/_protected/settings/people'
      path: '/settings/people'
      fullPath: '/settings/people'
      preLoaderRoute: typeof ProtectedSettingsPeopleRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/notifications': {
      id: '/_protected/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof ProtectedSettingsNotificationsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/integrations': {
      id: '/_protected/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof ProtectedSettingsIntegrationsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/general': {
      id: '/_protected/settings/general'
      path: '/settings/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof ProtectedSettingsGeneralRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/data': {
      id: '/_protected/settings/data'
      path: '/settings/data'
      fullPath: '/settings/data'
      preLoaderRoute: typeof ProtectedSettingsDataRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/danger': {
      id: '/_protected/settings/danger'
      path: '/settings/danger'
      fullPath: '/settings/danger'
      preLoaderRoute: typeof ProtectedSettingsDangerRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/connections': {
      id: '/_protected/settings/connections'
      path: '/settings/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof ProtectedSettingsConnectionsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/billing': {
      id: '/_protected/settings/billing'
      path: '/settings/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof ProtectedSettingsBillingRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/account': {
      id: '/_protected/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof ProtectedSettingsAccountRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/people/staff': {
      id: '/_protected/people/staff'
      path: '/staff'
      fullPath: '/people/staff'
      preLoaderRoute: typeof ProtectedPeopleStaffRouteImport
      parentRoute: typeof ProtectedPeopleRoute
    }
    '/_protected/people/reporting': {
      id: '/_protected/people/reporting'
      path: '/reporting'
      fullPath: '/people/reporting'
      preLoaderRoute: typeof ProtectedPeopleReportingRouteImport
      parentRoute: typeof ProtectedPeopleRoute
    }
    '/_protected/people/parents': {
      id: '/_protected/people/parents'
      path: '/parents'
      fullPath: '/people/parents'
      preLoaderRoute: typeof ProtectedPeopleParentsRouteImport
      parentRoute: typeof ProtectedPeopleRoute
    }
    '/_protected/people/new': {
      id: '/_protected/people/new'
      path: '/new'
      fullPath: '/people/new'
      preLoaderRoute: typeof ProtectedPeopleNewRouteImport
      parentRoute: typeof ProtectedPeopleRoute
    }
    '/_protected/people/department': {
      id: '/_protected/people/department'
      path: '/department'
      fullPath: '/people/department'
      preLoaderRoute: typeof ProtectedPeopleDepartmentRouteImport
      parentRoute: typeof ProtectedPeopleRoute
    }
    '/_protected/people/attendance': {
      id: '/_protected/people/attendance'
      path: '/attendance'
      fullPath: '/people/attendance'
      preLoaderRoute: typeof ProtectedPeopleAttendanceRouteImport
      parentRoute: typeof ProtectedPeopleRoute
    }
    '/_protected/people/assignments': {
      id: '/_protected/people/assignments'
      path: '/assignments'
      fullPath: '/people/assignments'
      preLoaderRoute: typeof ProtectedPeopleAssignmentsRouteImport
      parentRoute: typeof ProtectedPeopleRoute
    }
    '/_protected/parent-portal/grades': {
      id: '/_protected/parent-portal/grades'
      path: '/grades'
      fullPath: '/parent-portal/grades'
      preLoaderRoute: typeof ProtectedParentPortalGradesRouteImport
      parentRoute: typeof ProtectedParentPortalRoute
    }
    '/_protected/parent-portal/fees': {
      id: '/_protected/parent-portal/fees'
      path: '/fees'
      fullPath: '/parent-portal/fees'
      preLoaderRoute: typeof ProtectedParentPortalFeesRouteImport
      parentRoute: typeof ProtectedParentPortalRoute
    }
    '/_protected/parent-portal/attendance': {
      id: '/_protected/parent-portal/attendance'
      path: '/attendance'
      fullPath: '/parent-portal/attendance'
      preLoaderRoute: typeof ProtectedParentPortalAttendanceRouteImport
      parentRoute: typeof ProtectedParentPortalRoute
    }
    '/_protected/messages/meetings': {
      id: '/_protected/messages/meetings'
      path: '/meetings'
      fullPath: '/messages/meetings'
      preLoaderRoute: typeof ProtectedMessagesMeetingsRouteImport
      parentRoute: typeof ProtectedMessagesRoute
    }
    '/_protected/messages/integrations': {
      id: '/_protected/messages/integrations'
      path: '/integrations'
      fullPath: '/messages/integrations'
      preLoaderRoute: typeof ProtectedMessagesIntegrationsRouteImport
      parentRoute: typeof ProtectedMessagesRoute
    }
    '/_protected/messages/inbox': {
      id: '/_protected/messages/inbox'
      path: '/inbox'
      fullPath: '/messages/inbox'
      preLoaderRoute: typeof ProtectedMessagesInboxRouteImport
      parentRoute: typeof ProtectedMessagesRoute
    }
    '/_protected/messages/announcements': {
      id: '/_protected/messages/announcements'
      path: '/announcements'
      fullPath: '/messages/announcements'
      preLoaderRoute: typeof ProtectedMessagesAnnouncementsRouteImport
      parentRoute: typeof ProtectedMessagesRoute
    }
    '/_protected/finance/tuitionandfees': {
      id: '/_protected/finance/tuitionandfees'
      path: '/tuitionandfees'
      fullPath: '/finance/tuitionandfees'
      preLoaderRoute: typeof ProtectedFinanceTuitionandfeesRouteImport
      parentRoute: typeof ProtectedFinanceRoute
    }
    '/_protected/finance/reports': {
      id: '/_protected/finance/reports'
      path: '/reports'
      fullPath: '/finance/reports'
      preLoaderRoute: typeof ProtectedFinanceReportsRouteImport
      parentRoute: typeof ProtectedFinanceRoute
    }
    '/_protected/finance/payroll': {
      id: '/_protected/finance/payroll'
      path: '/payroll'
      fullPath: '/finance/payroll'
      preLoaderRoute: typeof ProtectedFinancePayrollRouteImport
      parentRoute: typeof ProtectedFinanceRoute
    }
    '/_protected/finance/financials': {
      id: '/_protected/finance/financials'
      path: '/financials'
      fullPath: '/finance/financials'
      preLoaderRoute: typeof ProtectedFinanceFinancialsRouteImport
      parentRoute: typeof ProtectedFinanceRoute
    }
    '/_protected/finance/expenses': {
      id: '/_protected/finance/expenses'
      path: '/expenses'
      fullPath: '/finance/expenses'
      preLoaderRoute: typeof ProtectedFinanceExpensesRouteImport
      parentRoute: typeof ProtectedFinanceRoute
    }
    '/_protected/analytics/financial': {
      id: '/_protected/analytics/financial'
      path: '/financial'
      fullPath: '/analytics/financial'
      preLoaderRoute: typeof ProtectedAnalyticsFinancialRouteImport
      parentRoute: typeof ProtectedAnalyticsRoute
    }
    '/_protected/analytics/academic': {
      id: '/_protected/analytics/academic'
      path: '/academic'
      fullPath: '/analytics/academic'
      preLoaderRoute: typeof ProtectedAnalyticsAcademicRouteImport
      parentRoute: typeof ProtectedAnalyticsRoute
    }
    '/_protected/academics/teachers': {
      id: '/_protected/academics/teachers'
      path: '/teachers'
      fullPath: '/academics/teachers'
      preLoaderRoute: typeof ProtectedAcademicsTeachersRouteImport
      parentRoute: typeof ProtectedAcademicsRoute
    }
    '/_protected/academics/students': {
      id: '/_protected/academics/students'
      path: '/students'
      fullPath: '/academics/students'
      preLoaderRoute: typeof ProtectedAcademicsStudentsRouteImport
      parentRoute: typeof ProtectedAcademicsRoute
    }
    '/_protected/academics/schoolcalendar': {
      id: '/_protected/academics/schoolcalendar'
      path: '/schoolcalendar'
      fullPath: '/academics/schoolcalendar'
      preLoaderRoute: typeof ProtectedAcademicsSchoolcalendarRouteImport
      parentRoute: typeof ProtectedAcademicsRoute
    }
    '/_protected/academics/reporting': {
      id: '/_protected/academics/reporting'
      path: '/reporting'
      fullPath: '/academics/reporting'
      preLoaderRoute: typeof ProtectedAcademicsReportingRouteImport
      parentRoute: typeof ProtectedAcademicsRoute
    }
    '/_protected/academics/gradelevels': {
      id: '/_protected/academics/gradelevels'
      path: '/gradelevels'
      fullPath: '/academics/gradelevels'
      preLoaderRoute: typeof ProtectedAcademicsGradelevelsRouteImport
      parentRoute: typeof ProtectedAcademicsRoute
    }
    '/_protected/academics/gradebooks': {
      id: '/_protected/academics/gradebooks'
      path: '/gradebooks'
      fullPath: '/academics/gradebooks'
      preLoaderRoute: typeof ProtectedAcademicsGradebooksRouteImport
      parentRoute: typeof ProtectedAcademicsRoute
    }
    '/_protected/academics/enrollment': {
      id: '/_protected/academics/enrollment'
      path: '/enrollment'
      fullPath: '/academics/enrollment'
      preLoaderRoute: typeof ProtectedAcademicsEnrollmentRouteImport
      parentRoute: typeof ProtectedAcademicsRoute
    }
    '/_protected/academics/curriculum': {
      id: '/_protected/academics/curriculum'
      path: '/curriculum'
      fullPath: '/academics/curriculum'
      preLoaderRoute: typeof ProtectedAcademicsCurriculumRouteImport
      parentRoute: typeof ProtectedAcademicsRoute
    }
    '/_protected/academics/classrooms': {
      id: '/_protected/academics/classrooms'
      path: '/classrooms'
      fullPath: '/academics/classrooms'
      preLoaderRoute: typeof ProtectedAcademicsClassroomsRouteImport
      parentRoute: typeof ProtectedAcademicsRoute
    }
    '/_protected/academics/attendance': {
      id: '/_protected/academics/attendance'
      path: '/attendance'
      fullPath: '/academics/attendance'
      preLoaderRoute: typeof ProtectedAcademicsAttendanceRouteImport
      parentRoute: typeof ProtectedAcademicsRoute
    }
    '/_protected/people/staff/$staffId': {
      id: '/_protected/people/staff/$staffId'
      path: '/$staffId'
      fullPath: '/people/staff/$staffId'
      preLoaderRoute: typeof ProtectedPeopleStaffStaffIdRouteImport
      parentRoute: typeof ProtectedPeopleStaffRoute
    }
    '/_protected/people/parents/$parentId': {
      id: '/_protected/people/parents/$parentId'
      path: '/$parentId'
      fullPath: '/people/parents/$parentId'
      preLoaderRoute: typeof ProtectedPeopleParentsParentIdRouteImport
      parentRoute: typeof ProtectedPeopleParentsRoute
    }
    '/_protected/academics/teachers/$teacherId': {
      id: '/_protected/academics/teachers/$teacherId'
      path: '/$teacherId'
      fullPath: '/academics/teachers/$teacherId'
      preLoaderRoute: typeof ProtectedAcademicsTeachersTeacherIdRouteImport
      parentRoute: typeof ProtectedAcademicsTeachersRoute
    }
    '/_protected/academics/students/$studentId': {
      id: '/_protected/academics/students/$studentId'
      path: '/$studentId'
      fullPath: '/academics/students/$studentId'
      preLoaderRoute: typeof ProtectedAcademicsStudentsStudentIdRouteImport
      parentRoute: typeof ProtectedAcademicsStudentsRoute
    }
    '/_protected/academics/gradebooks/$classId': {
      id: '/_protected/academics/gradebooks/$classId'
      path: '/$classId'
      fullPath: '/academics/gradebooks/$classId'
      preLoaderRoute: typeof ProtectedAcademicsGradebooksClassIdRouteImport
      parentRoute: typeof ProtectedAcademicsGradebooksRoute
    }
    '/_protected/academics/classrooms/$classroomId': {
      id: '/_protected/academics/classrooms/$classroomId'
      path: '/$classroomId'
      fullPath: '/academics/classrooms/$classroomId'
      preLoaderRoute: typeof ProtectedAcademicsClassroomsClassroomIdRouteImport
      parentRoute: typeof ProtectedAcademicsClassroomsRoute
    }
  }
}

interface ProtectedAcademicsClassroomsRouteChildren {
  ProtectedAcademicsClassroomsClassroomIdRoute: typeof ProtectedAcademicsClassroomsClassroomIdRoute
}

const ProtectedAcademicsClassroomsRouteChildren: ProtectedAcademicsClassroomsRouteChildren =
  {
    ProtectedAcademicsClassroomsClassroomIdRoute:
      ProtectedAcademicsClassroomsClassroomIdRoute,
  }

const ProtectedAcademicsClassroomsRouteWithChildren =
  ProtectedAcademicsClassroomsRoute._addFileChildren(
    ProtectedAcademicsClassroomsRouteChildren,
  )

interface ProtectedAcademicsGradebooksRouteChildren {
  ProtectedAcademicsGradebooksClassIdRoute: typeof ProtectedAcademicsGradebooksClassIdRoute
}

const ProtectedAcademicsGradebooksRouteChildren: ProtectedAcademicsGradebooksRouteChildren =
  {
    ProtectedAcademicsGradebooksClassIdRoute:
      ProtectedAcademicsGradebooksClassIdRoute,
  }

const ProtectedAcademicsGradebooksRouteWithChildren =
  ProtectedAcademicsGradebooksRoute._addFileChildren(
    ProtectedAcademicsGradebooksRouteChildren,
  )

interface ProtectedAcademicsStudentsRouteChildren {
  ProtectedAcademicsStudentsStudentIdRoute: typeof ProtectedAcademicsStudentsStudentIdRoute
}

const ProtectedAcademicsStudentsRouteChildren: ProtectedAcademicsStudentsRouteChildren =
  {
    ProtectedAcademicsStudentsStudentIdRoute:
      ProtectedAcademicsStudentsStudentIdRoute,
  }

const ProtectedAcademicsStudentsRouteWithChildren =
  ProtectedAcademicsStudentsRoute._addFileChildren(
    ProtectedAcademicsStudentsRouteChildren,
  )

interface ProtectedAcademicsTeachersRouteChildren {
  ProtectedAcademicsTeachersTeacherIdRoute: typeof ProtectedAcademicsTeachersTeacherIdRoute
}

const ProtectedAcademicsTeachersRouteChildren: ProtectedAcademicsTeachersRouteChildren =
  {
    ProtectedAcademicsTeachersTeacherIdRoute:
      ProtectedAcademicsTeachersTeacherIdRoute,
  }

const ProtectedAcademicsTeachersRouteWithChildren =
  ProtectedAcademicsTeachersRoute._addFileChildren(
    ProtectedAcademicsTeachersRouteChildren,
  )

interface ProtectedAcademicsRouteChildren {
  ProtectedAcademicsAttendanceRoute: typeof ProtectedAcademicsAttendanceRoute
  ProtectedAcademicsClassroomsRoute: typeof ProtectedAcademicsClassroomsRouteWithChildren
  ProtectedAcademicsCurriculumRoute: typeof ProtectedAcademicsCurriculumRoute
  ProtectedAcademicsEnrollmentRoute: typeof ProtectedAcademicsEnrollmentRoute
  ProtectedAcademicsGradebooksRoute: typeof ProtectedAcademicsGradebooksRouteWithChildren
  ProtectedAcademicsGradelevelsRoute: typeof ProtectedAcademicsGradelevelsRoute
  ProtectedAcademicsReportingRoute: typeof ProtectedAcademicsReportingRoute
  ProtectedAcademicsSchoolcalendarRoute: typeof ProtectedAcademicsSchoolcalendarRoute
  ProtectedAcademicsStudentsRoute: typeof ProtectedAcademicsStudentsRouteWithChildren
  ProtectedAcademicsTeachersRoute: typeof ProtectedAcademicsTeachersRouteWithChildren
}

const ProtectedAcademicsRouteChildren: ProtectedAcademicsRouteChildren = {
  ProtectedAcademicsAttendanceRoute: ProtectedAcademicsAttendanceRoute,
  ProtectedAcademicsClassroomsRoute:
    ProtectedAcademicsClassroomsRouteWithChildren,
  ProtectedAcademicsCurriculumRoute: ProtectedAcademicsCurriculumRoute,
  ProtectedAcademicsEnrollmentRoute: ProtectedAcademicsEnrollmentRoute,
  ProtectedAcademicsGradebooksRoute:
    ProtectedAcademicsGradebooksRouteWithChildren,
  ProtectedAcademicsGradelevelsRoute: ProtectedAcademicsGradelevelsRoute,
  ProtectedAcademicsReportingRoute: ProtectedAcademicsReportingRoute,
  ProtectedAcademicsSchoolcalendarRoute: ProtectedAcademicsSchoolcalendarRoute,
  ProtectedAcademicsStudentsRoute: ProtectedAcademicsStudentsRouteWithChildren,
  ProtectedAcademicsTeachersRoute: ProtectedAcademicsTeachersRouteWithChildren,
}

const ProtectedAcademicsRouteWithChildren =
  ProtectedAcademicsRoute._addFileChildren(ProtectedAcademicsRouteChildren)

interface ProtectedAnalyticsRouteChildren {
  ProtectedAnalyticsAcademicRoute: typeof ProtectedAnalyticsAcademicRoute
  ProtectedAnalyticsFinancialRoute: typeof ProtectedAnalyticsFinancialRoute
}

const ProtectedAnalyticsRouteChildren: ProtectedAnalyticsRouteChildren = {
  ProtectedAnalyticsAcademicRoute: ProtectedAnalyticsAcademicRoute,
  ProtectedAnalyticsFinancialRoute: ProtectedAnalyticsFinancialRoute,
}

const ProtectedAnalyticsRouteWithChildren =
  ProtectedAnalyticsRoute._addFileChildren(ProtectedAnalyticsRouteChildren)

interface ProtectedFinanceRouteChildren {
  ProtectedFinanceExpensesRoute: typeof ProtectedFinanceExpensesRoute
  ProtectedFinanceFinancialsRoute: typeof ProtectedFinanceFinancialsRoute
  ProtectedFinancePayrollRoute: typeof ProtectedFinancePayrollRoute
  ProtectedFinanceReportsRoute: typeof ProtectedFinanceReportsRoute
  ProtectedFinanceTuitionandfeesRoute: typeof ProtectedFinanceTuitionandfeesRoute
}

const ProtectedFinanceRouteChildren: ProtectedFinanceRouteChildren = {
  ProtectedFinanceExpensesRoute: ProtectedFinanceExpensesRoute,
  ProtectedFinanceFinancialsRoute: ProtectedFinanceFinancialsRoute,
  ProtectedFinancePayrollRoute: ProtectedFinancePayrollRoute,
  ProtectedFinanceReportsRoute: ProtectedFinanceReportsRoute,
  ProtectedFinanceTuitionandfeesRoute: ProtectedFinanceTuitionandfeesRoute,
}

const ProtectedFinanceRouteWithChildren =
  ProtectedFinanceRoute._addFileChildren(ProtectedFinanceRouteChildren)

interface ProtectedMessagesRouteChildren {
  ProtectedMessagesAnnouncementsRoute: typeof ProtectedMessagesAnnouncementsRoute
  ProtectedMessagesInboxRoute: typeof ProtectedMessagesInboxRoute
  ProtectedMessagesIntegrationsRoute: typeof ProtectedMessagesIntegrationsRoute
  ProtectedMessagesMeetingsRoute: typeof ProtectedMessagesMeetingsRoute
  ProtectedMessagesIndexRoute: typeof ProtectedMessagesIndexRoute
}

const ProtectedMessagesRouteChildren: ProtectedMessagesRouteChildren = {
  ProtectedMessagesAnnouncementsRoute: ProtectedMessagesAnnouncementsRoute,
  ProtectedMessagesInboxRoute: ProtectedMessagesInboxRoute,
  ProtectedMessagesIntegrationsRoute: ProtectedMessagesIntegrationsRoute,
  ProtectedMessagesMeetingsRoute: ProtectedMessagesMeetingsRoute,
  ProtectedMessagesIndexRoute: ProtectedMessagesIndexRoute,
}

const ProtectedMessagesRouteWithChildren =
  ProtectedMessagesRoute._addFileChildren(ProtectedMessagesRouteChildren)

interface ProtectedParentPortalRouteChildren {
  ProtectedParentPortalAttendanceRoute: typeof ProtectedParentPortalAttendanceRoute
  ProtectedParentPortalFeesRoute: typeof ProtectedParentPortalFeesRoute
  ProtectedParentPortalGradesRoute: typeof ProtectedParentPortalGradesRoute
}

const ProtectedParentPortalRouteChildren: ProtectedParentPortalRouteChildren = {
  ProtectedParentPortalAttendanceRoute: ProtectedParentPortalAttendanceRoute,
  ProtectedParentPortalFeesRoute: ProtectedParentPortalFeesRoute,
  ProtectedParentPortalGradesRoute: ProtectedParentPortalGradesRoute,
}

const ProtectedParentPortalRouteWithChildren =
  ProtectedParentPortalRoute._addFileChildren(
    ProtectedParentPortalRouteChildren,
  )

interface ProtectedPeopleParentsRouteChildren {
  ProtectedPeopleParentsParentIdRoute: typeof ProtectedPeopleParentsParentIdRoute
}

const ProtectedPeopleParentsRouteChildren: ProtectedPeopleParentsRouteChildren =
  {
    ProtectedPeopleParentsParentIdRoute: ProtectedPeopleParentsParentIdRoute,
  }

const ProtectedPeopleParentsRouteWithChildren =
  ProtectedPeopleParentsRoute._addFileChildren(
    ProtectedPeopleParentsRouteChildren,
  )

interface ProtectedPeopleStaffRouteChildren {
  ProtectedPeopleStaffStaffIdRoute: typeof ProtectedPeopleStaffStaffIdRoute
}

const ProtectedPeopleStaffRouteChildren: ProtectedPeopleStaffRouteChildren = {
  ProtectedPeopleStaffStaffIdRoute: ProtectedPeopleStaffStaffIdRoute,
}

const ProtectedPeopleStaffRouteWithChildren =
  ProtectedPeopleStaffRoute._addFileChildren(ProtectedPeopleStaffRouteChildren)

interface ProtectedPeopleRouteChildren {
  ProtectedPeopleAssignmentsRoute: typeof ProtectedPeopleAssignmentsRoute
  ProtectedPeopleAttendanceRoute: typeof ProtectedPeopleAttendanceRoute
  ProtectedPeopleDepartmentRoute: typeof ProtectedPeopleDepartmentRoute
  ProtectedPeopleNewRoute: typeof ProtectedPeopleNewRoute
  ProtectedPeopleParentsRoute: typeof ProtectedPeopleParentsRouteWithChildren
  ProtectedPeopleReportingRoute: typeof ProtectedPeopleReportingRoute
  ProtectedPeopleStaffRoute: typeof ProtectedPeopleStaffRouteWithChildren
}

const ProtectedPeopleRouteChildren: ProtectedPeopleRouteChildren = {
  ProtectedPeopleAssignmentsRoute: ProtectedPeopleAssignmentsRoute,
  ProtectedPeopleAttendanceRoute: ProtectedPeopleAttendanceRoute,
  ProtectedPeopleDepartmentRoute: ProtectedPeopleDepartmentRoute,
  ProtectedPeopleNewRoute: ProtectedPeopleNewRoute,
  ProtectedPeopleParentsRoute: ProtectedPeopleParentsRouteWithChildren,
  ProtectedPeopleReportingRoute: ProtectedPeopleReportingRoute,
  ProtectedPeopleStaffRoute: ProtectedPeopleStaffRouteWithChildren,
}

const ProtectedPeopleRouteWithChildren = ProtectedPeopleRoute._addFileChildren(
  ProtectedPeopleRouteChildren,
)

interface ProtectedStudentPortalRouteChildren {
  ProtectedStudentPortalAssignmentsRoute: typeof ProtectedStudentPortalAssignmentsRoute
  ProtectedStudentPortalAttendanceRoute: typeof ProtectedStudentPortalAttendanceRoute
  ProtectedStudentPortalGradesRoute: typeof ProtectedStudentPortalGradesRoute
  ProtectedStudentPortalScheduleRoute: typeof ProtectedStudentPortalScheduleRoute
}

const ProtectedStudentPortalRouteChildren: ProtectedStudentPortalRouteChildren =
  {
    ProtectedStudentPortalAssignmentsRoute:
      ProtectedStudentPortalAssignmentsRoute,
    ProtectedStudentPortalAttendanceRoute:
      ProtectedStudentPortalAttendanceRoute,
    ProtectedStudentPortalGradesRoute: ProtectedStudentPortalGradesRoute,
    ProtectedStudentPortalScheduleRoute: ProtectedStudentPortalScheduleRoute,
  }

const ProtectedStudentPortalRouteWithChildren =
  ProtectedStudentPortalRoute._addFileChildren(
    ProtectedStudentPortalRouteChildren,
  )

interface ProtectedRouteChildren {
  ProtectedAcademicsRoute: typeof ProtectedAcademicsRouteWithChildren
  ProtectedAnalyticsRoute: typeof ProtectedAnalyticsRouteWithChildren
  ProtectedFinanceRoute: typeof ProtectedFinanceRouteWithChildren
  ProtectedHomeRoute: typeof ProtectedHomeRoute
  ProtectedMessagesRoute: typeof ProtectedMessagesRouteWithChildren
  ProtectedParentPortalRoute: typeof ProtectedParentPortalRouteWithChildren
  ProtectedPeopleRoute: typeof ProtectedPeopleRouteWithChildren
  ProtectedStudentPortalRoute: typeof ProtectedStudentPortalRouteWithChildren
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedSettingsAccountRoute: typeof ProtectedSettingsAccountRoute
  ProtectedSettingsBillingRoute: typeof ProtectedSettingsBillingRoute
  ProtectedSettingsConnectionsRoute: typeof ProtectedSettingsConnectionsRoute
  ProtectedSettingsDangerRoute: typeof ProtectedSettingsDangerRoute
  ProtectedSettingsDataRoute: typeof ProtectedSettingsDataRoute
  ProtectedSettingsGeneralRoute: typeof ProtectedSettingsGeneralRoute
  ProtectedSettingsIntegrationsRoute: typeof ProtectedSettingsIntegrationsRoute
  ProtectedSettingsNotificationsRoute: typeof ProtectedSettingsNotificationsRoute
  ProtectedSettingsPeopleRoute: typeof ProtectedSettingsPeopleRoute
  ProtectedSettingsPreferencesRoute: typeof ProtectedSettingsPreferencesRoute
  ProtectedSettingsSchoolsRoute: typeof ProtectedSettingsSchoolsRoute
  ProtectedSettingsSecurityRoute: typeof ProtectedSettingsSecurityRoute
  ProtectedSettingsIndexRoute: typeof ProtectedSettingsIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAcademicsRoute: ProtectedAcademicsRouteWithChildren,
  ProtectedAnalyticsRoute: ProtectedAnalyticsRouteWithChildren,
  ProtectedFinanceRoute: ProtectedFinanceRouteWithChildren,
  ProtectedHomeRoute: ProtectedHomeRoute,
  ProtectedMessagesRoute: ProtectedMessagesRouteWithChildren,
  ProtectedParentPortalRoute: ProtectedParentPortalRouteWithChildren,
  ProtectedPeopleRoute: ProtectedPeopleRouteWithChildren,
  ProtectedStudentPortalRoute: ProtectedStudentPortalRouteWithChildren,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedSettingsAccountRoute: ProtectedSettingsAccountRoute,
  ProtectedSettingsBillingRoute: ProtectedSettingsBillingRoute,
  ProtectedSettingsConnectionsRoute: ProtectedSettingsConnectionsRoute,
  ProtectedSettingsDangerRoute: ProtectedSettingsDangerRoute,
  ProtectedSettingsDataRoute: ProtectedSettingsDataRoute,
  ProtectedSettingsGeneralRoute: ProtectedSettingsGeneralRoute,
  ProtectedSettingsIntegrationsRoute: ProtectedSettingsIntegrationsRoute,
  ProtectedSettingsNotificationsRoute: ProtectedSettingsNotificationsRoute,
  ProtectedSettingsPeopleRoute: ProtectedSettingsPeopleRoute,
  ProtectedSettingsPreferencesRoute: ProtectedSettingsPreferencesRoute,
  ProtectedSettingsSchoolsRoute: ProtectedSettingsSchoolsRoute,
  ProtectedSettingsSecurityRoute: ProtectedSettingsSecurityRoute,
  ProtectedSettingsIndexRoute: ProtectedSettingsIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
  LoginRoute: LoginRoute,
  MissingTenantRoute: MissingTenantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
