/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MissingTenantRouteImport } from './routes/missing-tenant'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedPeopleRouteImport } from './routes/_protected/people'
import { Route as ProtectedHomeRouteImport } from './routes/_protected/home'
import { Route as ProtectedFinanceRouteImport } from './routes/_protected/finance'
import { Route as ProtectedAcademicsRouteImport } from './routes/_protected/academics'
import { Route as ProtectedSettingsIndexRouteImport } from './routes/_protected/settings/index'
import { Route as ProtectedPeopleStaffRouteImport } from './routes/_protected/people/staff'
import { Route as ProtectedPeopleReportingRouteImport } from './routes/_protected/people/reporting'
import { Route as ProtectedPeopleParentsRouteImport } from './routes/_protected/people/parents'
import { Route as ProtectedPeopleNewRouteImport } from './routes/_protected/people/new'
import { Route as ProtectedPeopleDepartmentRouteImport } from './routes/_protected/people/department'
import { Route as ProtectedPeopleAttendanceRouteImport } from './routes/_protected/people/attendance'
import { Route as ProtectedPeopleAssignmentsRouteImport } from './routes/_protected/people/assignments'
import { Route as ProtectedFinanceTuitionandfeesRouteImport } from './routes/_protected/finance/tuitionandfees'
import { Route as ProtectedFinanceReportsRouteImport } from './routes/_protected/finance/reports'
import { Route as ProtectedFinancePayrollRouteImport } from './routes/_protected/finance/payroll'
import { Route as ProtectedFinanceFinancialsRouteImport } from './routes/_protected/finance/financials'
import { Route as ProtectedFinanceExpensesRouteImport } from './routes/_protected/finance/expenses'
import { Route as ProtectedAcademicsTeachersRouteImport } from './routes/_protected/academics/teachers'
import { Route as ProtectedAcademicsStudentsRouteImport } from './routes/_protected/academics/students'
import { Route as ProtectedAcademicsSchoolcalendarRouteImport } from './routes/_protected/academics/schoolcalendar'
import { Route as ProtectedAcademicsReportingRouteImport } from './routes/_protected/academics/reporting'
import { Route as ProtectedAcademicsGradelevelsRouteImport } from './routes/_protected/academics/gradelevels'
import { Route as ProtectedAcademicsEnrollmentRouteImport } from './routes/_protected/academics/enrollment'
import { Route as ProtectedAcademicsCurriculumRouteImport } from './routes/_protected/academics/curriculum'
import { Route as ProtectedAcademicsClassroomsRouteImport } from './routes/_protected/academics/classrooms'
import { Route as ProtectedAcademicsAttendanceRouteImport } from './routes/_protected/academics/attendance'

const MissingTenantRoute = MissingTenantRouteImport.update({
  id: '/missing-tenant',
  path: '/missing-tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPeopleRoute = ProtectedPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedHomeRoute = ProtectedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedFinanceRoute = ProtectedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAcademicsRoute = ProtectedAcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsIndexRoute = ProtectedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPeopleStaffRoute = ProtectedPeopleStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => ProtectedPeopleRoute,
} as any)
const ProtectedPeopleReportingRoute =
  ProtectedPeopleReportingRouteImport.update({
    id: '/reporting',
    path: '/reporting',
    getParentRoute: () => ProtectedPeopleRoute,
  } as any)
const ProtectedPeopleParentsRoute = ProtectedPeopleParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => ProtectedPeopleRoute,
} as any)
const ProtectedPeopleNewRoute = ProtectedPeopleNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProtectedPeopleRoute,
} as any)
const ProtectedPeopleDepartmentRoute =
  ProtectedPeopleDepartmentRouteImport.update({
    id: '/department',
    path: '/department',
    getParentRoute: () => ProtectedPeopleRoute,
  } as any)
const ProtectedPeopleAttendanceRoute =
  ProtectedPeopleAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => ProtectedPeopleRoute,
  } as any)
const ProtectedPeopleAssignmentsRoute =
  ProtectedPeopleAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => ProtectedPeopleRoute,
  } as any)
const ProtectedFinanceTuitionandfeesRoute =
  ProtectedFinanceTuitionandfeesRouteImport.update({
    id: '/tuitionandfees',
    path: '/tuitionandfees',
    getParentRoute: () => ProtectedFinanceRoute,
  } as any)
const ProtectedFinanceReportsRoute = ProtectedFinanceReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ProtectedFinanceRoute,
} as any)
const ProtectedFinancePayrollRoute = ProtectedFinancePayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => ProtectedFinanceRoute,
} as any)
const ProtectedFinanceFinancialsRoute =
  ProtectedFinanceFinancialsRouteImport.update({
    id: '/financials',
    path: '/financials',
    getParentRoute: () => ProtectedFinanceRoute,
  } as any)
const ProtectedFinanceExpensesRoute =
  ProtectedFinanceExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => ProtectedFinanceRoute,
  } as any)
const ProtectedAcademicsTeachersRoute =
  ProtectedAcademicsTeachersRouteImport.update({
    id: '/teachers',
    path: '/teachers',
    getParentRoute: () => ProtectedAcademicsRoute,
  } as any)
const ProtectedAcademicsStudentsRoute =
  ProtectedAcademicsStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => ProtectedAcademicsRoute,
  } as any)
const ProtectedAcademicsSchoolcalendarRoute =
  ProtectedAcademicsSchoolcalendarRouteImport.update({
    id: '/schoolcalendar',
    path: '/schoolcalendar',
    getParentRoute: () => ProtectedAcademicsRoute,
  } as any)
const ProtectedAcademicsReportingRoute =
  ProtectedAcademicsReportingRouteImport.update({
    id: '/reporting',
    path: '/reporting',
    getParentRoute: () => ProtectedAcademicsRoute,
  } as any)
const ProtectedAcademicsGradelevelsRoute =
  ProtectedAcademicsGradelevelsRouteImport.update({
    id: '/gradelevels',
    path: '/gradelevels',
    getParentRoute: () => ProtectedAcademicsRoute,
  } as any)
const ProtectedAcademicsEnrollmentRoute =
  ProtectedAcademicsEnrollmentRouteImport.update({
    id: '/enrollment',
    path: '/enrollment',
    getParentRoute: () => ProtectedAcademicsRoute,
  } as any)
const ProtectedAcademicsCurriculumRoute =
  ProtectedAcademicsCurriculumRouteImport.update({
    id: '/curriculum',
    path: '/curriculum',
    getParentRoute: () => ProtectedAcademicsRoute,
  } as any)
const ProtectedAcademicsClassroomsRoute =
  ProtectedAcademicsClassroomsRouteImport.update({
    id: '/classrooms',
    path: '/classrooms',
    getParentRoute: () => ProtectedAcademicsRoute,
  } as any)
const ProtectedAcademicsAttendanceRoute =
  ProtectedAcademicsAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => ProtectedAcademicsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/missing-tenant': typeof MissingTenantRoute
  '/academics': typeof ProtectedAcademicsRouteWithChildren
  '/finance': typeof ProtectedFinanceRouteWithChildren
  '/home': typeof ProtectedHomeRoute
  '/people': typeof ProtectedPeopleRouteWithChildren
  '/': typeof ProtectedIndexRoute
  '/academics/attendance': typeof ProtectedAcademicsAttendanceRoute
  '/academics/classrooms': typeof ProtectedAcademicsClassroomsRoute
  '/academics/curriculum': typeof ProtectedAcademicsCurriculumRoute
  '/academics/enrollment': typeof ProtectedAcademicsEnrollmentRoute
  '/academics/gradelevels': typeof ProtectedAcademicsGradelevelsRoute
  '/academics/reporting': typeof ProtectedAcademicsReportingRoute
  '/academics/schoolcalendar': typeof ProtectedAcademicsSchoolcalendarRoute
  '/academics/students': typeof ProtectedAcademicsStudentsRoute
  '/academics/teachers': typeof ProtectedAcademicsTeachersRoute
  '/finance/expenses': typeof ProtectedFinanceExpensesRoute
  '/finance/financials': typeof ProtectedFinanceFinancialsRoute
  '/finance/payroll': typeof ProtectedFinancePayrollRoute
  '/finance/reports': typeof ProtectedFinanceReportsRoute
  '/finance/tuitionandfees': typeof ProtectedFinanceTuitionandfeesRoute
  '/people/assignments': typeof ProtectedPeopleAssignmentsRoute
  '/people/attendance': typeof ProtectedPeopleAttendanceRoute
  '/people/department': typeof ProtectedPeopleDepartmentRoute
  '/people/new': typeof ProtectedPeopleNewRoute
  '/people/parents': typeof ProtectedPeopleParentsRoute
  '/people/reporting': typeof ProtectedPeopleReportingRoute
  '/people/staff': typeof ProtectedPeopleStaffRoute
  '/settings': typeof ProtectedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/missing-tenant': typeof MissingTenantRoute
  '/academics': typeof ProtectedAcademicsRouteWithChildren
  '/finance': typeof ProtectedFinanceRouteWithChildren
  '/home': typeof ProtectedHomeRoute
  '/people': typeof ProtectedPeopleRouteWithChildren
  '/': typeof ProtectedIndexRoute
  '/academics/attendance': typeof ProtectedAcademicsAttendanceRoute
  '/academics/classrooms': typeof ProtectedAcademicsClassroomsRoute
  '/academics/curriculum': typeof ProtectedAcademicsCurriculumRoute
  '/academics/enrollment': typeof ProtectedAcademicsEnrollmentRoute
  '/academics/gradelevels': typeof ProtectedAcademicsGradelevelsRoute
  '/academics/reporting': typeof ProtectedAcademicsReportingRoute
  '/academics/schoolcalendar': typeof ProtectedAcademicsSchoolcalendarRoute
  '/academics/students': typeof ProtectedAcademicsStudentsRoute
  '/academics/teachers': typeof ProtectedAcademicsTeachersRoute
  '/finance/expenses': typeof ProtectedFinanceExpensesRoute
  '/finance/financials': typeof ProtectedFinanceFinancialsRoute
  '/finance/payroll': typeof ProtectedFinancePayrollRoute
  '/finance/reports': typeof ProtectedFinanceReportsRoute
  '/finance/tuitionandfees': typeof ProtectedFinanceTuitionandfeesRoute
  '/people/assignments': typeof ProtectedPeopleAssignmentsRoute
  '/people/attendance': typeof ProtectedPeopleAttendanceRoute
  '/people/department': typeof ProtectedPeopleDepartmentRoute
  '/people/new': typeof ProtectedPeopleNewRoute
  '/people/parents': typeof ProtectedPeopleParentsRoute
  '/people/reporting': typeof ProtectedPeopleReportingRoute
  '/people/staff': typeof ProtectedPeopleStaffRoute
  '/settings': typeof ProtectedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/missing-tenant': typeof MissingTenantRoute
  '/_protected/academics': typeof ProtectedAcademicsRouteWithChildren
  '/_protected/finance': typeof ProtectedFinanceRouteWithChildren
  '/_protected/home': typeof ProtectedHomeRoute
  '/_protected/people': typeof ProtectedPeopleRouteWithChildren
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/academics/attendance': typeof ProtectedAcademicsAttendanceRoute
  '/_protected/academics/classrooms': typeof ProtectedAcademicsClassroomsRoute
  '/_protected/academics/curriculum': typeof ProtectedAcademicsCurriculumRoute
  '/_protected/academics/enrollment': typeof ProtectedAcademicsEnrollmentRoute
  '/_protected/academics/gradelevels': typeof ProtectedAcademicsGradelevelsRoute
  '/_protected/academics/reporting': typeof ProtectedAcademicsReportingRoute
  '/_protected/academics/schoolcalendar': typeof ProtectedAcademicsSchoolcalendarRoute
  '/_protected/academics/students': typeof ProtectedAcademicsStudentsRoute
  '/_protected/academics/teachers': typeof ProtectedAcademicsTeachersRoute
  '/_protected/finance/expenses': typeof ProtectedFinanceExpensesRoute
  '/_protected/finance/financials': typeof ProtectedFinanceFinancialsRoute
  '/_protected/finance/payroll': typeof ProtectedFinancePayrollRoute
  '/_protected/finance/reports': typeof ProtectedFinanceReportsRoute
  '/_protected/finance/tuitionandfees': typeof ProtectedFinanceTuitionandfeesRoute
  '/_protected/people/assignments': typeof ProtectedPeopleAssignmentsRoute
  '/_protected/people/attendance': typeof ProtectedPeopleAttendanceRoute
  '/_protected/people/department': typeof ProtectedPeopleDepartmentRoute
  '/_protected/people/new': typeof ProtectedPeopleNewRoute
  '/_protected/people/parents': typeof ProtectedPeopleParentsRoute
  '/_protected/people/reporting': typeof ProtectedPeopleReportingRoute
  '/_protected/people/staff': typeof ProtectedPeopleStaffRoute
  '/_protected/settings/': typeof ProtectedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/forbidden'
    | '/login'
    | '/missing-tenant'
    | '/academics'
    | '/finance'
    | '/home'
    | '/people'
    | '/'
    | '/academics/attendance'
    | '/academics/classrooms'
    | '/academics/curriculum'
    | '/academics/enrollment'
    | '/academics/gradelevels'
    | '/academics/reporting'
    | '/academics/schoolcalendar'
    | '/academics/students'
    | '/academics/teachers'
    | '/finance/expenses'
    | '/finance/financials'
    | '/finance/payroll'
    | '/finance/reports'
    | '/finance/tuitionandfees'
    | '/people/assignments'
    | '/people/attendance'
    | '/people/department'
    | '/people/new'
    | '/people/parents'
    | '/people/reporting'
    | '/people/staff'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forbidden'
    | '/login'
    | '/missing-tenant'
    | '/academics'
    | '/finance'
    | '/home'
    | '/people'
    | '/'
    | '/academics/attendance'
    | '/academics/classrooms'
    | '/academics/curriculum'
    | '/academics/enrollment'
    | '/academics/gradelevels'
    | '/academics/reporting'
    | '/academics/schoolcalendar'
    | '/academics/students'
    | '/academics/teachers'
    | '/finance/expenses'
    | '/finance/financials'
    | '/finance/payroll'
    | '/finance/reports'
    | '/finance/tuitionandfees'
    | '/people/assignments'
    | '/people/attendance'
    | '/people/department'
    | '/people/new'
    | '/people/parents'
    | '/people/reporting'
    | '/people/staff'
    | '/settings'
  id:
    | '__root__'
    | '/_protected'
    | '/forbidden'
    | '/login'
    | '/missing-tenant'
    | '/_protected/academics'
    | '/_protected/finance'
    | '/_protected/home'
    | '/_protected/people'
    | '/_protected/'
    | '/_protected/academics/attendance'
    | '/_protected/academics/classrooms'
    | '/_protected/academics/curriculum'
    | '/_protected/academics/enrollment'
    | '/_protected/academics/gradelevels'
    | '/_protected/academics/reporting'
    | '/_protected/academics/schoolcalendar'
    | '/_protected/academics/students'
    | '/_protected/academics/teachers'
    | '/_protected/finance/expenses'
    | '/_protected/finance/financials'
    | '/_protected/finance/payroll'
    | '/_protected/finance/reports'
    | '/_protected/finance/tuitionandfees'
    | '/_protected/people/assignments'
    | '/_protected/people/attendance'
    | '/_protected/people/department'
    | '/_protected/people/new'
    | '/_protected/people/parents'
    | '/_protected/people/reporting'
    | '/_protected/people/staff'
    | '/_protected/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
  LoginRoute: typeof LoginRoute
  MissingTenantRoute: typeof MissingTenantRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/missing-tenant': {
      id: '/missing-tenant'
      path: '/missing-tenant'
      fullPath: '/missing-tenant'
      preLoaderRoute: typeof MissingTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/people': {
      id: '/_protected/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof ProtectedPeopleRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/home': {
      id: '/_protected/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof ProtectedHomeRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/finance': {
      id: '/_protected/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof ProtectedFinanceRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/academics': {
      id: '/_protected/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof ProtectedAcademicsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/': {
      id: '/_protected/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/people/staff': {
      id: '/_protected/people/staff'
      path: '/staff'
      fullPath: '/people/staff'
      preLoaderRoute: typeof ProtectedPeopleStaffRouteImport
      parentRoute: typeof ProtectedPeopleRoute
    }
    '/_protected/people/reporting': {
      id: '/_protected/people/reporting'
      path: '/reporting'
      fullPath: '/people/reporting'
      preLoaderRoute: typeof ProtectedPeopleReportingRouteImport
      parentRoute: typeof ProtectedPeopleRoute
    }
    '/_protected/people/parents': {
      id: '/_protected/people/parents'
      path: '/parents'
      fullPath: '/people/parents'
      preLoaderRoute: typeof ProtectedPeopleParentsRouteImport
      parentRoute: typeof ProtectedPeopleRoute
    }
    '/_protected/people/new': {
      id: '/_protected/people/new'
      path: '/new'
      fullPath: '/people/new'
      preLoaderRoute: typeof ProtectedPeopleNewRouteImport
      parentRoute: typeof ProtectedPeopleRoute
    }
    '/_protected/people/department': {
      id: '/_protected/people/department'
      path: '/department'
      fullPath: '/people/department'
      preLoaderRoute: typeof ProtectedPeopleDepartmentRouteImport
      parentRoute: typeof ProtectedPeopleRoute
    }
    '/_protected/people/attendance': {
      id: '/_protected/people/attendance'
      path: '/attendance'
      fullPath: '/people/attendance'
      preLoaderRoute: typeof ProtectedPeopleAttendanceRouteImport
      parentRoute: typeof ProtectedPeopleRoute
    }
    '/_protected/people/assignments': {
      id: '/_protected/people/assignments'
      path: '/assignments'
      fullPath: '/people/assignments'
      preLoaderRoute: typeof ProtectedPeopleAssignmentsRouteImport
      parentRoute: typeof ProtectedPeopleRoute
    }
    '/_protected/finance/tuitionandfees': {
      id: '/_protected/finance/tuitionandfees'
      path: '/tuitionandfees'
      fullPath: '/finance/tuitionandfees'
      preLoaderRoute: typeof ProtectedFinanceTuitionandfeesRouteImport
      parentRoute: typeof ProtectedFinanceRoute
    }
    '/_protected/finance/reports': {
      id: '/_protected/finance/reports'
      path: '/reports'
      fullPath: '/finance/reports'
      preLoaderRoute: typeof ProtectedFinanceReportsRouteImport
      parentRoute: typeof ProtectedFinanceRoute
    }
    '/_protected/finance/payroll': {
      id: '/_protected/finance/payroll'
      path: '/payroll'
      fullPath: '/finance/payroll'
      preLoaderRoute: typeof ProtectedFinancePayrollRouteImport
      parentRoute: typeof ProtectedFinanceRoute
    }
    '/_protected/finance/financials': {
      id: '/_protected/finance/financials'
      path: '/financials'
      fullPath: '/finance/financials'
      preLoaderRoute: typeof ProtectedFinanceFinancialsRouteImport
      parentRoute: typeof ProtectedFinanceRoute
    }
    '/_protected/finance/expenses': {
      id: '/_protected/finance/expenses'
      path: '/expenses'
      fullPath: '/finance/expenses'
      preLoaderRoute: typeof ProtectedFinanceExpensesRouteImport
      parentRoute: typeof ProtectedFinanceRoute
    }
    '/_protected/academics/teachers': {
      id: '/_protected/academics/teachers'
      path: '/teachers'
      fullPath: '/academics/teachers'
      preLoaderRoute: typeof ProtectedAcademicsTeachersRouteImport
      parentRoute: typeof ProtectedAcademicsRoute
    }
    '/_protected/academics/students': {
      id: '/_protected/academics/students'
      path: '/students'
      fullPath: '/academics/students'
      preLoaderRoute: typeof ProtectedAcademicsStudentsRouteImport
      parentRoute: typeof ProtectedAcademicsRoute
    }
    '/_protected/academics/schoolcalendar': {
      id: '/_protected/academics/schoolcalendar'
      path: '/schoolcalendar'
      fullPath: '/academics/schoolcalendar'
      preLoaderRoute: typeof ProtectedAcademicsSchoolcalendarRouteImport
      parentRoute: typeof ProtectedAcademicsRoute
    }
    '/_protected/academics/reporting': {
      id: '/_protected/academics/reporting'
      path: '/reporting'
      fullPath: '/academics/reporting'
      preLoaderRoute: typeof ProtectedAcademicsReportingRouteImport
      parentRoute: typeof ProtectedAcademicsRoute
    }
    '/_protected/academics/gradelevels': {
      id: '/_protected/academics/gradelevels'
      path: '/gradelevels'
      fullPath: '/academics/gradelevels'
      preLoaderRoute: typeof ProtectedAcademicsGradelevelsRouteImport
      parentRoute: typeof ProtectedAcademicsRoute
    }
    '/_protected/academics/enrollment': {
      id: '/_protected/academics/enrollment'
      path: '/enrollment'
      fullPath: '/academics/enrollment'
      preLoaderRoute: typeof ProtectedAcademicsEnrollmentRouteImport
      parentRoute: typeof ProtectedAcademicsRoute
    }
    '/_protected/academics/curriculum': {
      id: '/_protected/academics/curriculum'
      path: '/curriculum'
      fullPath: '/academics/curriculum'
      preLoaderRoute: typeof ProtectedAcademicsCurriculumRouteImport
      parentRoute: typeof ProtectedAcademicsRoute
    }
    '/_protected/academics/classrooms': {
      id: '/_protected/academics/classrooms'
      path: '/classrooms'
      fullPath: '/academics/classrooms'
      preLoaderRoute: typeof ProtectedAcademicsClassroomsRouteImport
      parentRoute: typeof ProtectedAcademicsRoute
    }
    '/_protected/academics/attendance': {
      id: '/_protected/academics/attendance'
      path: '/attendance'
      fullPath: '/academics/attendance'
      preLoaderRoute: typeof ProtectedAcademicsAttendanceRouteImport
      parentRoute: typeof ProtectedAcademicsRoute
    }
  }
}

interface ProtectedAcademicsRouteChildren {
  ProtectedAcademicsAttendanceRoute: typeof ProtectedAcademicsAttendanceRoute
  ProtectedAcademicsClassroomsRoute: typeof ProtectedAcademicsClassroomsRoute
  ProtectedAcademicsCurriculumRoute: typeof ProtectedAcademicsCurriculumRoute
  ProtectedAcademicsEnrollmentRoute: typeof ProtectedAcademicsEnrollmentRoute
  ProtectedAcademicsGradelevelsRoute: typeof ProtectedAcademicsGradelevelsRoute
  ProtectedAcademicsReportingRoute: typeof ProtectedAcademicsReportingRoute
  ProtectedAcademicsSchoolcalendarRoute: typeof ProtectedAcademicsSchoolcalendarRoute
  ProtectedAcademicsStudentsRoute: typeof ProtectedAcademicsStudentsRoute
  ProtectedAcademicsTeachersRoute: typeof ProtectedAcademicsTeachersRoute
}

const ProtectedAcademicsRouteChildren: ProtectedAcademicsRouteChildren = {
  ProtectedAcademicsAttendanceRoute: ProtectedAcademicsAttendanceRoute,
  ProtectedAcademicsClassroomsRoute: ProtectedAcademicsClassroomsRoute,
  ProtectedAcademicsCurriculumRoute: ProtectedAcademicsCurriculumRoute,
  ProtectedAcademicsEnrollmentRoute: ProtectedAcademicsEnrollmentRoute,
  ProtectedAcademicsGradelevelsRoute: ProtectedAcademicsGradelevelsRoute,
  ProtectedAcademicsReportingRoute: ProtectedAcademicsReportingRoute,
  ProtectedAcademicsSchoolcalendarRoute: ProtectedAcademicsSchoolcalendarRoute,
  ProtectedAcademicsStudentsRoute: ProtectedAcademicsStudentsRoute,
  ProtectedAcademicsTeachersRoute: ProtectedAcademicsTeachersRoute,
}

const ProtectedAcademicsRouteWithChildren =
  ProtectedAcademicsRoute._addFileChildren(ProtectedAcademicsRouteChildren)

interface ProtectedFinanceRouteChildren {
  ProtectedFinanceExpensesRoute: typeof ProtectedFinanceExpensesRoute
  ProtectedFinanceFinancialsRoute: typeof ProtectedFinanceFinancialsRoute
  ProtectedFinancePayrollRoute: typeof ProtectedFinancePayrollRoute
  ProtectedFinanceReportsRoute: typeof ProtectedFinanceReportsRoute
  ProtectedFinanceTuitionandfeesRoute: typeof ProtectedFinanceTuitionandfeesRoute
}

const ProtectedFinanceRouteChildren: ProtectedFinanceRouteChildren = {
  ProtectedFinanceExpensesRoute: ProtectedFinanceExpensesRoute,
  ProtectedFinanceFinancialsRoute: ProtectedFinanceFinancialsRoute,
  ProtectedFinancePayrollRoute: ProtectedFinancePayrollRoute,
  ProtectedFinanceReportsRoute: ProtectedFinanceReportsRoute,
  ProtectedFinanceTuitionandfeesRoute: ProtectedFinanceTuitionandfeesRoute,
}

const ProtectedFinanceRouteWithChildren =
  ProtectedFinanceRoute._addFileChildren(ProtectedFinanceRouteChildren)

interface ProtectedPeopleRouteChildren {
  ProtectedPeopleAssignmentsRoute: typeof ProtectedPeopleAssignmentsRoute
  ProtectedPeopleAttendanceRoute: typeof ProtectedPeopleAttendanceRoute
  ProtectedPeopleDepartmentRoute: typeof ProtectedPeopleDepartmentRoute
  ProtectedPeopleNewRoute: typeof ProtectedPeopleNewRoute
  ProtectedPeopleParentsRoute: typeof ProtectedPeopleParentsRoute
  ProtectedPeopleReportingRoute: typeof ProtectedPeopleReportingRoute
  ProtectedPeopleStaffRoute: typeof ProtectedPeopleStaffRoute
}

const ProtectedPeopleRouteChildren: ProtectedPeopleRouteChildren = {
  ProtectedPeopleAssignmentsRoute: ProtectedPeopleAssignmentsRoute,
  ProtectedPeopleAttendanceRoute: ProtectedPeopleAttendanceRoute,
  ProtectedPeopleDepartmentRoute: ProtectedPeopleDepartmentRoute,
  ProtectedPeopleNewRoute: ProtectedPeopleNewRoute,
  ProtectedPeopleParentsRoute: ProtectedPeopleParentsRoute,
  ProtectedPeopleReportingRoute: ProtectedPeopleReportingRoute,
  ProtectedPeopleStaffRoute: ProtectedPeopleStaffRoute,
}

const ProtectedPeopleRouteWithChildren = ProtectedPeopleRoute._addFileChildren(
  ProtectedPeopleRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedAcademicsRoute: typeof ProtectedAcademicsRouteWithChildren
  ProtectedFinanceRoute: typeof ProtectedFinanceRouteWithChildren
  ProtectedHomeRoute: typeof ProtectedHomeRoute
  ProtectedPeopleRoute: typeof ProtectedPeopleRouteWithChildren
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedSettingsIndexRoute: typeof ProtectedSettingsIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAcademicsRoute: ProtectedAcademicsRouteWithChildren,
  ProtectedFinanceRoute: ProtectedFinanceRouteWithChildren,
  ProtectedHomeRoute: ProtectedHomeRoute,
  ProtectedPeopleRoute: ProtectedPeopleRouteWithChildren,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedSettingsIndexRoute: ProtectedSettingsIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
  LoginRoute: LoginRoute,
  MissingTenantRoute: MissingTenantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
